In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
import re

In [3]:
INVENTORY_FILE = Path(
    "data/idx_dataset_inventory.csv"
)

DATA_ROOT = Path(
    "data/idx_financial_statements"
)

print("Inventory exists:", INVENTORY_FILE.exists())
print("Data root exists:", DATA_ROOT.exists())

Inventory exists: True
Data root exists: True

In [4]:
inventory_df = pd.read_csv(
    INVENTORY_FILE
)

print(
    "Total files:",
    len(inventory_df)
)

display(
    inventory_df.head()
)

Total files: 114366

,file_path,file_name,extension,size_mb,year,quarter
0,data\idx_financial_statements\Financial_Statem...,AADI.zip,.zip,4.045,2025,NaN
1,data\idx_financial_statements\Financial_Statem...,BBRI.zip,.zip,8.324,2025,NaN
2,data\idx_financial_statements\Financial_Statem...,ZYRX_2025_Q1_FinancialStatement-2025-I-ZYRX.pdf,.pdf,0.805,2025,Q1
3,data\idx_financial_statements\Financial_Statem...,ZYRX_2025_Q1_FS.xlsx,.xlsx,0.338,2025,Q1
4,data\idx_financial_statements\Financial_Statem...,ZYRX_2025_Q1_Instance.zip,.zip,0.123,2025,Q1

In [5]:
xlsx_df = inventory_df[
    inventory_df["extension"]
    .str.lower()
    .eq(".xlsx")
].copy()

print(
    "Total XLSX files:",
    len(xlsx_df)
)

display(
    xlsx_df.head(20)
)

Total XLSX files: 16003

,file_path,file_name,extension,size_mb,year,quarter
3,data\idx_financial_statements\Financial_Statem...,ZYRX_2025_Q1_FS.xlsx,.xlsx,0.338,2025,Q1
12,data\idx_financial_statements\Financial_Statem...,ZONE_2025_Q1_FS.xlsx,.xlsx,0.340,2025,Q1
18,data\idx_financial_statements\Financial_Statem...,ZINC_2025_Q1_FS.xlsx,.xlsx,0.339,2025,Q1
24,data\idx_financial_statements\Financial_Statem...,ZATA_2025_Q1_FS.xlsx,.xlsx,0.304,2025,Q1
29,data\idx_financial_statements\Financial_Statem...,YUPI_2025_Q1_FS.xlsx,.xlsx,0.342,2025,Q1
37,data\idx_financial_statements\Financial_Statem...,YULE_2025_Q1_FS.xlsx,.xlsx,0.164,2025,Q1
43,data\idx_financial_statements\Financial_Statem...,YPAS_2025_Q1_FS.xlsx,.xlsx,0.340,2025,Q1
49,data\idx_financial_statements\Financial_Statem...,YOII_2025_Q1_FS.xlsx,.xlsx,0.115,2025,Q1
54,data\idx_financial_statements\Financial_Statem...,YELO_2025_Q1_FS.xlsx,.xlsx,0.316,2025,Q1
59,data\idx_financial_statements\Financial_Statem...,WTON_2025_Q1_FS.xlsx,.xlsx,0.371,2025,Q1
67,data\idx_financial_statements\Financial_Statem...,WSKT_2025_Q1_FS.xlsx,.xlsx,0.367,2025,Q1
73,data\idx_financial_statements\Financial_Statem...,WSBP_2025_Q1_FS.xlsx,.xlsx,0.322,2025,Q1
77,data\idx_financial_statements\Financial_Statem...,WOWS_2025_Q1_FS.xlsx,.xlsx,0.292,2025,Q1
82,data\idx_financial_statements\Financial_Statem...,WOOD_2025_Q1_FS.xlsx,.xlsx,0.408,2025,Q1
95,data\idx_financial_statements\Financial_Statem...,WMUU_2025_Q1_FS.xlsx,.xlsx,0.307,2025,Q1
105,data\idx_financial_statements\Financial_Statem...,WIRG_2025_Q1_FS.xlsx,.xlsx,0.344,2025,Q1
110,data\idx_financial_statements\Financial_Statem...,WINS_2025_Q1_FS.xlsx,.xlsx,0.347,2025,Q1
116,data\idx_financial_statements\Financial_Statem...,WINR_2025_Q1_FS.xlsx,.xlsx,0.306,2025,Q1
125,data\idx_financial_statements\Financial_Statem...,WINE_2025_Q1_FS.xlsx,.xlsx,0.342,2025,Q1
129,data\idx_financial_statements\Financial_Statem...,WIKA_2025_Q1_FS.xlsx,.xlsx,0.000,2025,Q1

In [6]:
def extract_ticker(file_name):
    if pd.isna(file_name):
        return None

    file_name = str(file_name)

    match = re.match(
        r"^([A-Z0-9]+)_",
        file_name.upper()
    )

    if match:
        return match.group(1)

    return None


xlsx_df["ticker"] = (
    xlsx_df["file_name"]
    .apply(extract_ticker)
)

display(
    xlsx_df[
        [
            "ticker",
            "year",
            "quarter",
            "file_name",
            "file_path"
        ]
    ].head(30)
)

,ticker,year,quarter,file_name,file_path
3,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
12,ZONE,2025,Q1,ZONE_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
18,ZINC,2025,Q1,ZINC_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
24,ZATA,2025,Q1,ZATA_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
29,YUPI,2025,Q1,YUPI_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
37,YULE,2025,Q1,YULE_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
43,YPAS,2025,Q1,YPAS_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
49,YOII,2025,Q1,YOII_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
54,YELO,2025,Q1,YELO_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
59,WTON,2025,Q1,WTON_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
67,WSKT,2025,Q1,WSKT_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
73,WSBP,2025,Q1,WSBP_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
77,WOWS,2025,Q1,WOWS_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
82,WOOD,2025,Q1,WOOD_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
95,WMUU,2025,Q1,WMUU_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
105,WIRG,2025,Q1,WIRG_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
110,WINS,2025,Q1,WINS_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
116,WINR,2025,Q1,WINR_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
125,WINE,2025,Q1,WINE_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
129,WIKA,2025,Q1,WIKA_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
136,WIIM,2025,Q1,WIIM_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
142,WIFI,2025,Q1,WIFI_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
149,WICO,2025,Q1,WICO_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
154,WEHA,2025,Q1,WEHA_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
160,WEGE,2025,Q1,WEGE_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
167,WAPO,2025,Q1,WAPO_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
176,VTNY,2025,Q1,VTNY_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
183,VRNA,2025,Q1,VRNA_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
190,VOKS,2025,Q1,VOKS_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
196,VKTR,2025,Q1,VKTR_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...

In [7]:
print(
    "Ticker detected:",
    xlsx_df["ticker"]
    .notna()
    .sum()
)

print(
    "Ticker missing:",
    xlsx_df["ticker"]
    .isna()
    .sum()
)

display(
    xlsx_df[
        xlsx_df["ticker"].isna()
    ].head(20)
)

Ticker detected: 16003
Ticker missing: 0

Empty DataFrame
Columns: [file_path, file_name, extension, size_mb, year, quarter, ticker]
Index: []

In [9]:
TEST_TICKERS = [
    "AADI",
    "BBRI",
    "AMRT",
    "TLKM",
    "KLBF"
]

test_files_df = (
    xlsx_df[
        xlsx_df["ticker"]
        .isin(TEST_TICKERS)
    ]
    .sort_values(
        [
            "ticker",
            "year",
            "quarter"
        ],
        ascending=[
            True,
            False,
            False
        ]
    )
)

display(
    test_files_df[
        [
            "ticker",
            "year",
            "quarter",
            "file_name",
            "file_path"
        ]
    ]
)

,ticker,year,quarter,file_name,file_path
5401,AADI,2025,Q1,AADI_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
29978,AADI,2024,Q4,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...,data\idx_financial_statements\Financial_Statem...
29980,AADI,2024,Q4,AADI_2024_Q4_FS.xlsx,data\idx_financial_statements\Financial_Statem...
5169,AMRT,2025,Q1,AMRT_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
28963,AMRT,2024,Q4,AMRT_2024_Q4_FS.xlsx,data\idx_financial_statements\Financial_Statem...
...,...,...,...,...,...
78220,TLKM,2021,Q1,TLKM_2021_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
97799,TLKM,2020,Q4,TLKM_2020_Q4_FS.xlsx,data\idx_financial_statements\Financial_Statem...
97794,TLKM,2020,Q3,TLKM_2020_Q3_FS.xlsx,data\idx_financial_statements\Financial_Statem...
97787,TLKM,2020,Q2,TLKM_2020_Q2_FS.xlsx,data\idx_financial_statements\Financial_Statem...
97781,TLKM,2020,Q1,TLKM_2020_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...

In [19]:
MIN_VALID_SIZE_MB = 0.01  # sekitar 10 KB

valid_test_files = (
    test_files_df[
        test_files_df["size_mb"] >= MIN_VALID_SIZE_MB
    ]
    .sort_values(
        ["ticker", "year", "quarter"],
        ascending=[True, False, False]
    )
)

latest_test_files = (
    valid_test_files
    .groupby(
        "ticker",
        as_index=False
    )
    .first()
)

display(
    latest_test_files[
        [
            "ticker",
            "year",
            "quarter",
            "file_name",
            "size_mb",
            "file_path"
        ]
    ]
)

,ticker,year,quarter,file_name,size_mb,file_path
0,AADI,2025,Q1,AADI_2025_Q1_FS.xlsx,0.344,data\idx_financial_statements\Financial_Statem...
1,AMRT,2024,Q4,AMRT_2024_Q4_FS.xlsx,0.348,data\idx_financial_statements\Financial_Statem...
2,BBRI,2025,Q1,BBRI_2025_Q1_FS.xlsx,0.129,data\idx_financial_statements\Financial_Statem...
3,KLBF,2025,Q1,KLBF_2025_Q1_FS.xlsx,0.341,data\idx_financial_statements\Financial_Statem...
4,TLKM,2025,Q1,TLKM_2025_Q1_FS.xlsx,0.295,data\idx_financial_statements\Financial_Statem...

In [20]:
def resolve_file_path(path_text):
    path = Path(path_text)

    if path.exists():
        return path

    alternative = Path.cwd() / path

    if alternative.exists():
        return alternative

    return None


latest_test_files[
    "resolved_path"
] = (
    latest_test_files[
        "file_path"
    ].apply(resolve_file_path)
)

display(
    latest_test_files[
        [
            "ticker",
            "file_name",
            "resolved_path"
        ]
    ]
)

,ticker,file_name,resolved_path
0,AADI,AADI_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
1,AMRT,AMRT_2024_Q4_FS.xlsx,data\idx_financial_statements\Financial_Statem...
2,BBRI,BBRI_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
3,KLBF,KLBF_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...
4,TLKM,TLKM_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...

In [21]:
for _, row in latest_test_files.iterrows():

    print(
        row["ticker"],
        "->",
        row["resolved_path"],
        "| exists:",
        row["resolved_path"] is not None
    )

AADI -> data\idx_financial_statements\Financial_Statement_2025_Q2\AADI\2025\Q1\AADI_2025_Q1_FS.xlsx | exists: True
AMRT -> data\idx_financial_statements\Financial_Statement_2024\AMRT\2024\Q4\AMRT_2024_Q4_FS.xlsx | exists: True
BBRI -> data\idx_financial_statements\Financial_Statement_2025_Q2\BBRI\2025\Q1\BBRI_2025_Q1_FS.xlsx | exists: True
KLBF -> data\idx_financial_statements\Financial_Statement_2025_Q2\KLBF\2025\Q1\KLBF_2025_Q1_FS.xlsx | exists: True
TLKM -> data\idx_financial_statements\Financial_Statement_2025_Q2\TLKM\2025\Q1\TLKM_2025_Q1_FS.xlsx | exists: True

In [26]:
failed_excel_files = []

for _, row in latest_test_files.iterrows():

    ticker = row["ticker"]
    file_path = row["resolved_path"]

    print("\n" + "=" * 80)
    print("TICKER:", ticker)
    print("FILE:", file_path)
    print("=" * 80)

    try:
        excel_file = pd.ExcelFile(
            file_path,
            engine="openpyxl"
        )

        for i, sheet in enumerate(
            excel_file.sheet_names
        ):
            print(
                i,
                "-",
                sheet
            )

    except Exception as e:

        print(
            "FAILED TO READ:",
            type(e).__name__,
            "-",
            e
        )

        failed_excel_files.append({
            "ticker": ticker,
            "file_path": str(file_path),
            "error_type": type(e).__name__,
            "error": str(e)
        })

================================================================================
TICKER: AADI
FILE: data\idx_financial_statements\Financial_Statement_2025_Q2\AADI\2025\Q1\AADI_2025_Q1_FS.xlsx
================================================================================
0 - Context
1 - InlineXBRL
2 - 1000000
3 - 1210000
4 - 1321000
5 - 1410000
6 - 1410000PY
7 - 1510000
8 - 1610000
9 - 1611000
10 - 1611000PY
11 - 1611100
12 - 1617000
13 - 1619000
14 - 1620100
15 - 1620200
16 - 1620500
17 - 1630000
18 - 1632000
19 - 1640100
20 - 1670000
21 - 1671000
22 - 1691000a
23 - 1691100
24 - 1692000
25 - 1693000
26 - 1693100
27 - 1696000
28 - hidden
29 - Token

================================================================================
TICKER: AMRT
FILE: data\idx_financial_statements\Financial_Statement_2024\AMRT\2024\Q4\AMRT_2024_Q4_FS.xlsx
================================================================================
0 - Context
1 - InlineXBRL
2 - 1000000
3 - 1210000
4 - 1311000
5 - 1410000
6 - 1410000PY
7 - 1510000
8 - 1610000
9 - 1611000
10 - 1611000PY
11 - 1611100
12 - 1612000
13 - 1612000PY
14 - 1616000
15 - 1620100
16 - 1621000a
17 - 1630000
18 - 1632000
19 - 1640100
20 - 1670000
21 - 1671000
22 - 1691000a
23 - 1691100
24 - 1692000
25 - 1693000
26 - 1693100
27 - 1696000
28 - hidden
29 - Token

================================================================================
TICKER: BBRI
FILE: data\idx_financial_statements\Financial_Statement_2025_Q2\BBRI\2025\Q1\BBRI_2025_Q1_FS.xlsx
================================================================================
0 - Context
1 - InlineXBRL
2 - 1000000
3 - 4220000
4 - 4312000
5 - 4410000
6 - 4410000PY
7 - 4510000
8 - 4610000
9 - 4611000
10 - 4611000PY
11 - 4611100
12 - hidden
13 - Token

================================================================================
TICKER: KLBF
FILE: data\idx_financial_statements\Financial_Statement_2025_Q2\KLBF\2025\Q1\KLBF_2025_Q1_FS.xlsx
================================================================================
0 - Context
1 - InlineXBRL
2 - 1000000
3 - 1210000
4 - 1311000
5 - 1410000
6 - 1410000PY
7 - 1510000
8 - 1610000
9 - 1611000
10 - 1611000PY
11 - 1611100
12 - 1612000
13 - 1612000PY
14 - 1617000
15 - 1618000
16 - 1620100
17 - 1620200
18 - 1630000
19 - 1632000
20 - 1640100
21 - 1670000
22 - 1671000
23 - 1691000a
24 - 1691100
25 - 1692000
26 - 1693000
27 - 1693100
28 - 1696000
29 - hidden
30 - Token

================================================================================
TICKER: TLKM
FILE: data\idx_financial_statements\Financial_Statement_2025_Q2\TLKM\2025\Q1\TLKM_2025_Q1_FS.xlsx
================================================================================
0 - Context
1 - InlineXBRL
2 - 1000000
3 - 3210000
4 - 3312000
5 - 3410000
6 - 3410000PY
7 - 3510000
8 - 3610000
9 - 3611000
10 - 3611000PY
11 - 3611100
12 - 3630000
13 - 3632000
14 - 3670000
15 - 3671000
16 - 3691000a
17 - 3691100
18 - 3692000
19 - 3693000
20 - 3693100
21 - 3696000
22 - hidden
23 - Token

In [27]:
failed_excel_df = pd.DataFrame(
    failed_excel_files
)

print(
    "Total failed files:",
    len(failed_excel_df)
)

display(
    failed_excel_df
)

Total failed files: 0

Empty DataFrame
Columns: []
Index: []

In [28]:
for _, row in latest_test_files.iterrows():

    file_path = row["resolved_path"]

    print(
        row["ticker"],
        "| size:",
        file_path.stat().st_size,
        "bytes"
    )

AADI | size: 360576 bytes
AMRT | size: 364769 bytes
BBRI | size: 135012 bytes
KLBF | size: 357935 bytes
TLKM | size: 309610 bytes

In [29]:
amrt_row = latest_test_files[
    latest_test_files["ticker"] == "AMRT"
].iloc[0]

amrt_path = amrt_row["resolved_path"]

with open(amrt_path, "rb") as f:
    raw = f.read()

print("Size:", len(raw), "bytes")
print("Raw content:")
print(raw)

Size: 364769 bytes
Raw content:

In [30]:
amrt_files = (
    xlsx_df[
        xlsx_df["ticker"] == "AMRT"
    ]
    .sort_values(
        ["year", "quarter"],
        ascending=[False, False]
    )
    .copy()
)

display(
    amrt_files[
        [
            "ticker",
            "year",
            "quarter",
            "file_name",
            "size_mb",
            "file_path"
        ]
    ]
)

,ticker,year,quarter,file_name,size_mb,file_path
5169,AMRT,2025,Q1,AMRT_2025_Q1_FS.xlsx,0.000,data\idx_financial_statements\Financial_Statem...
28963,AMRT,2024,Q4,AMRT_2024_Q4_FS.xlsx,0.348,data\idx_financial_statements\Financial_Statem...
28954,AMRT,2024,Q3,AMRT_2024_Q3_FS.xlsx,0.347,data\idx_financial_statements\Financial_Statem...
28948,AMRT,2024,Q2,AMRT_2024_Q2_FS.xlsx,0.342,data\idx_financial_statements\Financial_Statem...
28941,AMRT,2024,Q1,AMRT_2024_Q1_FS.xlsx,0.325,data\idx_financial_statements\Financial_Statem...
53482,AMRT,2023,Q4,AMRT_2023_Q4_FS.xlsx,0.185,data\idx_financial_statements\Financial_Statem...
53471,AMRT,2023,Q3,AMRT_2023_Q3_FS.xlsx,1.131,data\idx_financial_statements\Financial_Statem...
53465,AMRT,2023,Q2,AMRT_2023_Q2_FS.xlsx,1.131,data\idx_financial_statements\Financial_Statem...
53458,AMRT,2023,Q1,AMRT_2023_Q1_FS.xlsx,1.131,data\idx_financial_statements\Financial_Statem...
75575,AMRT,2022,Q4,AMRT_2022_Q4_FS.xlsx,1.130,data\idx_financial_statements\Financial_Statem...
75568,AMRT,2022,Q3,AMRT_2022_Q3_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
75563,AMRT,2022,Q2,AMRT_2022_Q2_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
75555,AMRT,2022,Q1,AMRT_2022_Q1_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
95442,AMRT,2021,Q4,AMRT_2021_Q4_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
95435,AMRT,2021,Q3,AMRT_2021_Q3_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
95428,AMRT,2021,Q2,AMRT_2021_Q2_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
95421,AMRT,2021,Q1,AMRT_2021_Q1_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
113526,AMRT,2020,Q4,AMRT_2020_Q4_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
113519,AMRT,2020,Q3,AMRT_2020_Q3_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
113512,AMRT,2020,Q2,AMRT_2020_Q2_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...
113505,AMRT,2020,Q1,AMRT_2020_Q1_FS.xlsx,0.152,data\idx_financial_statements\Financial_Statem...