In [1]:
# Keep repository-relative paths valid from notebook subfolders.
from pathlib import Path
import os

os.chdir(next(
    root for root in (Path.cwd(), *Path.cwd().parents)
    if (root / "notebooks").is_dir() and (root / "requirements.txt").is_file()
))

# Resolve legacy IDX paths stored in existing CSVs without rewriting the data.
def _relocated_idx_path(value):
    text = str(value).replace("\\", "/")
    old_repo = "AI-Builders-Hackhaton-2026-Backend/"
    if old_repo in text:
        text = text.split(old_repo, 1)[1]
    old_raw = "data/idx_financial_statements/"
    if text.startswith(old_raw):
        text = "data/idx_financial/raw/" + text[len(old_raw):]
    return Path(text)

# CELL 1 - IMPORT AND LOAD FINAL NORMALIZED IDX DATASET

from pathlib import Path

import numpy as np
import pandas as pd


FINAL_NORMALIZED_FILE = Path(
    "data/idx_financial/normalized/idx_financial_metrics_normalized_final.csv"
)


idx_normalized_df = pd.read_csv(
    FINAL_NORMALIZED_FILE,
    low_memory=False
)


print(
    "Loaded:",
    FINAL_NORMALIZED_FILE
)

print(
    "Rows:",
    len(idx_normalized_df)
)

print(
    "Unique tickers:",
    idx_normalized_df[
        "ticker"
    ].nunique()
)

print(
    "Unique source files:",
    idx_normalized_df[
        "source_file"
    ].nunique()
)

Loaded: data\idx_financial_metrics_normalized_final.csv
Rows: 83442
Unique tickers: 924
Unique source files: 14755

In [2]:
# CELL 2 - VALIDATE FINAL NORMALIZED DATASET

required_columns = [
    "ticker",
    "year",
    "quarter",
    "metric",
    "normalized_value",
    "currency",
    "source_file"
]


missing_columns = [
    column
    for column in required_columns
    if column not in idx_normalized_df.columns
]


print(
    "Missing required columns:",
    missing_columns
)


print(
    "\nMissing normalized values:",
    idx_normalized_df[
        "normalized_value"
    ].isna().sum()
)


print(
    "\nDuplicate ticker/year/quarter/metric:",
    idx_normalized_df[
        [
            "ticker",
            "year",
            "quarter",
            "metric"
        ]
    ].duplicated().sum()
)


print("\nMETRIC COUNTS")

print(
    idx_normalized_df[
        "metric"
    ].value_counts()
)


print("\nCURRENCY COUNTS")

print(
    idx_normalized_df[
        "currency"
    ].value_counts(
        dropna=False
    )
)

Missing required columns: []

Missing normalized values: 4

Duplicate ticker/year/quarter/metric: 0

METRIC COUNTS
metric
total_assets           14754
total_liabilities      14754
operating_cash_flow    14738
cash                   13779
revenue                13003
gross_profit           12414
Name: count, dtype: int64

CURRENCY COUNTS
currency
IDR    73034
USD    10404
NaN        4
Name: count, dtype: int64

In [3]:
# CELL 3 - PIVOT NORMALIZED METRICS TO TICKER-PERIOD LEVEL

metric_wide_df = (
    idx_normalized_df
    .pivot_table(
        index=[
            "ticker",
            "year",
            "quarter"
        ],
        columns="metric",
        values="normalized_value",
        aggfunc="first"
    )
    .reset_index()
)


metric_wide_df.columns.name = None


print(
    "Ticker-period rows:",
    len(metric_wide_df)
)

print(
    "Unique tickers:",
    metric_wide_df[
        "ticker"
    ].nunique()
)


print("\nCOLUMNS")

print(
    metric_wide_df.columns.tolist()
)


display(
    metric_wide_df.head(10)
)

Ticker-period rows: 14753
Unique tickers: 924

COLUMNS
['ticker', 'year', 'quarter', 'cash', 'gross_profit', 'operating_cash_flow', 'revenue', 'total_assets', 'total_liabilities']

,ticker,year,quarter,cash,gross_profit,operating_cash_flow,revenue,total_assets,total_liabilities
0,AADI,2024,Q4,1.518688e+09,1.465951e+09,1.198515e+09,5.319582e+09,5.992658e+09,2.629176e+09
1,AADI,2025,Q1,1.358333e+09,3.474080e+08,3.266550e+08,1.164437e+09,5.827769e+09,2.339594e+09
2,AALI,2020,Q1,1.470866e+12,9.267910e+11,6.606100e+11,4.796084e+12,2.921860e+13,9.854949e+12
3,AALI,2020,Q2,1.152117e+12,1.303517e+12,1.573827e+12,9.081017e+12,2.738127e+13,8.061912e+12
4,AALI,2020,Q4,9.788920e+11,2.962891e+12,2.322164e+12,1.880704e+13,2.778123e+13,8.533437e+12
5,AALI,2021,Q1,1.810842e+12,9.321850e+11,1.004935e+12,5.035167e+12,2.846902e+13,8.820539e+12
6,AALI,2021,Q2,2.532318e+12,2.214032e+12,2.399195e+12,1.083208e+13,2.868902e+13,8.741617e+12
7,AALI,2021,Q3,3.874116e+12,3.611195e+12,4.138836e+12,1.801447e+13,2.969401e+13,9.114312e+12
8,AALI,2021,Q4,3.896022e+12,4.830014e+12,4.895119e+12,2.432205e+13,3.039991e+13,9.228733e+12
9,AALI,2022,Q1,3.993025e+12,9.943630e+11,3.189140e+11,6.581321e+12,3.123278e+13,9.525261e+12

In [4]:
# CELL 4 - CALCULATE SAFE FINANCIAL RATIOS

benchmark_ratio_df = (
    metric_wide_df
    .copy()
)


def safe_divide(
    numerator,
    denominator
):
    numerator = pd.to_numeric(
        numerator,
        errors="coerce"
    )

    denominator = pd.to_numeric(
        denominator,
        errors="coerce"
    )

    result = np.where(
        (
            numerator.notna()
        )
        &
        (
            denominator.notna()
        )
        &
        (
            denominator != 0
        ),
        numerator / denominator,
        np.nan
    )

    return result


# Gross Margin
benchmark_ratio_df[
    "gross_margin"
] = safe_divide(
    benchmark_ratio_df.get(
        "gross_profit"
    ),
    benchmark_ratio_df.get(
        "revenue"
    )
)


# Debt to Assets
benchmark_ratio_df[
    "debt_to_assets"
] = safe_divide(
    benchmark_ratio_df.get(
        "total_liabilities"
    ),
    benchmark_ratio_df.get(
        "total_assets"
    )
)


# Cash to Assets
benchmark_ratio_df[
    "cash_to_assets"
] = safe_divide(
    benchmark_ratio_df.get(
        "cash"
    ),
    benchmark_ratio_df.get(
        "total_assets"
    )
)


# Operating Cash Flow to Revenue
benchmark_ratio_df[
    "ocf_to_revenue"
] = safe_divide(
    benchmark_ratio_df.get(
        "operating_cash_flow"
    ),
    benchmark_ratio_df.get(
        "revenue"
    )
)


ratio_columns = [
    "gross_margin",
    "debt_to_assets",
    "cash_to_assets",
    "ocf_to_revenue"
]


print("RATIO AVAILABILITY")

for ratio in ratio_columns:

    print(
        ratio,
        ":",
        benchmark_ratio_df[
            ratio
        ].notna().sum()
    )


display(
    benchmark_ratio_df[
        [
            "ticker",
            "year",
            "quarter",
            *ratio_columns
        ]
    ].head(20)
)

RATIO AVAILABILITY
gross_margin : 12349
debt_to_assets : 14753
cash_to_assets : 13778
ocf_to_revenue : 12963

,ticker,year,quarter,gross_margin,debt_to_assets,cash_to_assets,ocf_to_revenue
0,AADI,2024,Q4,0.275576,0.438733,0.253425,0.225302
1,AADI,2025,Q1,0.298348,0.401456,0.233079,0.280526
2,AALI,2020,Q1,0.193239,0.337283,0.050340,0.137739
3,AALI,2020,Q2,0.143543,0.294432,0.042077,0.173310
4,AALI,2020,Q4,0.157542,0.307166,0.035236,0.123473
5,AALI,2021,Q1,0.185135,0.309829,0.063607,0.199583
6,AALI,2021,Q2,0.204396,0.304703,0.088268,0.221490
7,AALI,2021,Q3,0.200461,0.306941,0.130468,0.229751
8,AALI,2021,Q4,0.198586,0.303578,0.128159,0.201263
9,AALI,2022,Q1,0.151089,0.304976,0.127847,0.048457
10,AALI,2022,Q2,0.166040,0.293868,0.064722,-0.053337
11,AALI,2022,Q3,0.161115,0.336589,0.149318,0.106274
12,AALI,2022,Q4,0.175097,0.239531,0.055373,0.084082
13,AALI,2023,Q1,0.107091,0.234797,0.065082,0.074089
14,AALI,2023,Q2,0.109413,0.247449,0.045560,0.082980
15,AALI,2023,Q3,0.124340,0.241488,0.085865,0.144759
16,AALI,2023,Q4,0.133570,0.217714,0.072436,0.122376
17,AALI,2024,Q2,0.124474,0.232792,0.134484,0.256157
18,AALI,2024,Q3,0.123153,0.213263,0.150009,0.246168
19,AALI,2024,Q4,0.153134,0.194183,0.112388,0.154902

In [5]:
# CELL 5 - AUDIT CALCULATED RATIOS

print("RATIO SUMMARY")
print("=" * 80)


for ratio in ratio_columns:

    print(
        f"\n{ratio}"
    )

    print(
        benchmark_ratio_df[
            ratio
        ].describe(
            percentiles=[
                0.01,
                0.05,
                0.25,
                0.50,
                0.75,
                0.95,
                0.99
            ]
        )
    )


print("\nEXTREME RATIO COUNTS")


ratio_extreme_summary = []


for ratio in ratio_columns:

    series = (
        benchmark_ratio_df[
            ratio
        ]
        .dropna()
    )

    ratio_extreme_summary.append(
        {
            "ratio": ratio,

            "count":
                len(series),

            "below_-5":
                (series < -5).sum(),

            "below_-1":
                (series < -1).sum(),

            "above_1":
                (series > 1).sum(),

            "above_5":
                (series > 5).sum(),
        }
    )


ratio_extreme_summary_df = (
    pd.DataFrame(
        ratio_extreme_summary
    )
)


display(
    ratio_extreme_summary_df
)

RATIO SUMMARY
================================================================================

gross_margin
count    12349.000000
mean        -8.930782
std        607.639880
min     -57082.968401
1%          -1.547849
5%          -0.008469
25%          0.125477
50%          0.250933
75%          0.436881
95%          0.701540
99%          1.000000
max          1.142575
Name: gross_margin, dtype: float64

debt_to_assets
count     14753.000000
mean         26.345292
std        2874.198656
min           0.000008
1%            0.009191
5%            0.069758
25%           0.255320
50%           0.450129
75%           0.660714
95%           1.021891
99%           3.952491
max      348997.678386
Name: debt_to_assets, dtype: float64

cash_to_assets
count    1.377800e+04
mean     1.323173e+01
std      1.541740e+03
min      1.151412e-07
1%       2.231454e-04
5%       1.764924e-03
25%      1.506969e-02
50%      5.232138e-02
75%      1.336428e-01
95%      3.274664e-01
99%      6.099653e-01
max      1.809691e+05
Name: cash_to_assets, dtype: float64

ocf_to_revenue
count    12963.000000
mean        -1.506380
std         90.973704
min      -7794.180297
1%          -5.662401
5%          -0.895640
25%         -0.044440
50%          0.060476
75%          0.199179
95%          0.556874
99%          1.263174
max        704.607807
Name: ocf_to_revenue, dtype: float64

EXTREME RATIO COUNTS

            ratio  count  below_-5  below_-1  above_1  above_5
0    gross_margin  12349        49       146        3        0
1  debt_to_assets  14753         0         0      764      123
2  cash_to_assets  13778         0         0        1        1
3  ocf_to_revenue  12963       148       607      176       38

In [6]:
# CELL 6 - BUILD METRIC-LEVEL PROVENANCE FOR RATIO AUDIT

value_pivot_df = (
    idx_normalized_df
    .pivot_table(
        index=[
            "ticker",
            "year",
            "quarter"
        ],
        columns="metric",
        values="normalized_value",
        aggfunc="first"
    )
    .reset_index()
)

value_pivot_df.columns.name = None


source_pivot_df = (
    idx_normalized_df
    .pivot_table(
        index=[
            "ticker",
            "year",
            "quarter"
        ],
        columns="metric",
        values="source_file",
        aggfunc="first"
    )
    .reset_index()
)

source_pivot_df.columns.name = None


# Rename source columns so they do not collide
source_metric_columns = [
    column
    for column in source_pivot_df.columns
    if column not in [
        "ticker",
        "year",
        "quarter"
    ]
]

source_pivot_df = source_pivot_df.rename(
    columns={
        column: f"{column}_source_file"
        for column in source_metric_columns
    }
)


ratio_audit_df = (
    value_pivot_df
    .merge(
        source_pivot_df,
        on=[
            "ticker",
            "year",
            "quarter"
        ],
        how="left",
        validate="one_to_one"
    )
)


print(
    "Ratio audit ticker-period rows:",
    len(ratio_audit_df)
)

print(
    "Unique tickers:",
    ratio_audit_df[
        "ticker"
    ].nunique()
)


display(
    ratio_audit_df.head()
)

Ratio audit ticker-period rows: 14753
Unique tickers: 924

,ticker,year,quarter,cash,gross_profit,operating_cash_flow,revenue,total_assets,total_liabilities,cash_source_file,gross_profit_source_file,operating_cash_flow_source_file,revenue_source_file,total_assets_source_file,total_liabilities_source_file
0,AADI,2024,Q4,1.518688e+09,1.465951e+09,1.198515e+09,5.319582e+09,5.992658e+09,2.629176e+09,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...,AADI_2024_Q4_FinancialStatement-2024-Tahunan-A...
1,AADI,2025,Q1,1.358333e+09,3.474080e+08,3.266550e+08,1.164437e+09,5.827769e+09,2.339594e+09,AADI_2025_Q1_FS.xlsx,AADI_2025_Q1_FS.xlsx,AADI_2025_Q1_FS.xlsx,AADI_2025_Q1_FS.xlsx,AADI_2025_Q1_FS.xlsx,AADI_2025_Q1_FS.xlsx
2,AALI,2020,Q1,1.470866e+12,9.267910e+11,6.606100e+11,4.796084e+12,2.921860e+13,9.854949e+12,AALI_2020_Q1_FS.xlsx,AALI_2020_Q1_FS.xlsx,AALI_2020_Q1_FS.xlsx,AALI_2020_Q1_FS.xlsx,AALI_2020_Q1_FS.xlsx,AALI_2020_Q1_FS.xlsx
3,AALI,2020,Q2,1.152117e+12,1.303517e+12,1.573827e+12,9.081017e+12,2.738127e+13,8.061912e+12,AALI_2020_Q2_FS.xlsx,AALI_2020_Q2_FS.xlsx,AALI_2020_Q2_FS.xlsx,AALI_2020_Q2_FS.xlsx,AALI_2020_Q2_FS.xlsx,AALI_2020_Q2_FS.xlsx
4,AALI,2020,Q4,9.788920e+11,2.962891e+12,2.322164e+12,1.880704e+13,2.778123e+13,8.533437e+12,AALI_2020_Q4_FS.xlsx,AALI_2020_Q4_FS.xlsx,AALI_2020_Q4_FS.xlsx,AALI_2020_Q4_FS.xlsx,AALI_2020_Q4_FS.xlsx,AALI_2020_Q4_FS.xlsx

In [7]:
# CELL 7 - CHECK SOURCE CONSISTENCY FOR EACH RATIO

ratio_audit_df[
    "gross_margin_same_source"
] = (
    ratio_audit_df[
        "gross_profit_source_file"
    ]
    ==
    ratio_audit_df[
        "revenue_source_file"
    ]
)


ratio_audit_df[
    "debt_to_assets_same_source"
] = (
    ratio_audit_df[
        "total_liabilities_source_file"
    ]
    ==
    ratio_audit_df[
        "total_assets_source_file"
    ]
)


ratio_audit_df[
    "cash_to_assets_same_source"
] = (
    ratio_audit_df[
        "cash_source_file"
    ]
    ==
    ratio_audit_df[
        "total_assets_source_file"
    ]
)


ratio_audit_df[
    "ocf_to_revenue_same_source"
] = (
    ratio_audit_df[
        "operating_cash_flow_source_file"
    ]
    ==
    ratio_audit_df[
        "revenue_source_file"
    ]
)


same_source_columns = [
    "gross_margin_same_source",
    "debt_to_assets_same_source",
    "cash_to_assets_same_source",
    "ocf_to_revenue_same_source"
]


print("SOURCE CONSISTENCY")

for column in same_source_columns:

    print(
        f"\n{column}"
    )

    print(
        ratio_audit_df[
            column
        ].value_counts(
            dropna=False
        )
    )

SOURCE CONSISTENCY

gross_margin_same_source
gross_margin_same_source
True     12374
False     2379
Name: count, dtype: int64

debt_to_assets_same_source
debt_to_assets_same_source
True    14753
Name: count, dtype: int64

cash_to_assets_same_source
cash_to_assets_same_source
True     13778
False      975
Name: count, dtype: int64

ocf_to_revenue_same_source
ocf_to_revenue_same_source
True     12990
False     1763
Name: count, dtype: int64

In [8]:
# CELL 8 - INSPECT EXTREME RATIO ROWS WITH PROVENANCE

ratio_audit_df[
    "gross_margin"
] = safe_divide(
    ratio_audit_df[
        "gross_profit"
    ],
    ratio_audit_df[
        "revenue"
    ]
)

ratio_audit_df[
    "debt_to_assets"
] = safe_divide(
    ratio_audit_df[
        "total_liabilities"
    ],
    ratio_audit_df[
        "total_assets"
    ]
)

ratio_audit_df[
    "cash_to_assets"
] = safe_divide(
    ratio_audit_df[
        "cash"
    ],
    ratio_audit_df[
        "total_assets"
    ]
)

ratio_audit_df[
    "ocf_to_revenue"
] = safe_divide(
    ratio_audit_df[
        "operating_cash_flow"
    ],
    ratio_audit_df[
        "revenue"
    ]
)


print("MOST EXTREME GROSS MARGIN")

display(
    ratio_audit_df[
        [
            "ticker",
            "year",
            "quarter",
            "gross_profit",
            "revenue",
            "gross_margin",
            "gross_profit_source_file",
            "revenue_source_file",
            "gross_margin_same_source"
        ]
    ]
    .sort_values(
        "gross_margin"
    )
    .head(20)
)


print("\nMOST EXTREME DEBT TO ASSETS")

display(
    ratio_audit_df[
        [
            "ticker",
            "year",
            "quarter",
            "total_liabilities",
            "total_assets",
            "debt_to_assets",
            "total_liabilities_source_file",
            "total_assets_source_file",
            "debt_to_assets_same_source"
        ]
    ]
    .sort_values(
        "debt_to_assets",
        ascending=False
    )
    .head(20)
)


print("\nMOST EXTREME CASH TO ASSETS")

display(
    ratio_audit_df[
        [
            "ticker",
            "year",
            "quarter",
            "cash",
            "total_assets",
            "cash_to_assets",
            "cash_source_file",
            "total_assets_source_file",
            "cash_to_assets_same_source"
        ]
    ]
    .sort_values(
        "cash_to_assets",
        ascending=False
    )
    .head(20)
)


print("\nMOST EXTREME OCF TO REVENUE")

ocf_extreme_df = (
    ratio_audit_df[
        [
            "ticker",
            "year",
            "quarter",
            "operating_cash_flow",
            "revenue",
            "ocf_to_revenue",
            "operating_cash_flow_source_file",
            "revenue_source_file",
            "ocf_to_revenue_same_source"
        ]
    ]
    .copy()
)

ocf_extreme_df[
    "abs_ocf_to_revenue"
] = (
    ocf_extreme_df[
        "ocf_to_revenue"
    ].abs()
)

display(
    ocf_extreme_df
    .sort_values(
        "abs_ocf_to_revenue",
        ascending=False
    )
    .head(20)
)

MOST EXTREME GROSS MARGIN

,ticker,year,quarter,gross_profit,revenue,gross_margin,gross_profit_source_file,revenue_source_file,gross_margin_same_source
5789,HDTX,2024,Q4,-3.071064e+10,538000.0,-57082.968401,HDTX_2024_Q4_FS.xlsx,HDTX_2024_Q4_FS.xlsx,True
5788,HDTX,2024,Q3,-1.834457e+10,538000.0,-34097.706320,HDTX_2024_Q3_FS.xlsx,HDTX_2024_Q3_FS.xlsx,True
5787,HDTX,2024,Q1,-6.065786e+09,538000.0,-11274.695167,HDTX_2024_Q1_FS.xlsx,HDTX_2024_Q1_FS.xlsx,True
7934,LAPD,2021,Q2,-1.591265e+10,8858115.0,-1796.392377,LAPD_2021_Q2_FS.xlsx,LAPD_2021_Q2_FS.xlsx,True
13411,TIRT,2023,Q4,-2.919396e+10,22360023.0,-1305.631795,TIRT_2023_Q4_FS.xlsx,TIRT_2023_Q4_FS.xlsx,True
5783,HDTX,2023,Q1,-6.848625e+09,5402000.0,-1267.794335,HDTX_2023_Q1_FS.xlsx,HDTX_2023_Q1_FS.xlsx,True
5784,HDTX,2023,Q2,-1.403996e+10,13241000.0,-1060.340080,HDTX_2023_Q2_FS.xlsx,HDTX_2023_Q2_FS.xlsx,True
5786,HDTX,2023,Q4,-2.948068e+10,27908000.0,-1056.352157,HDTX_2023_Q4_FS.xlsx,HDTX_2023_Q4_FS.xlsx,True
13410,TIRT,2023,Q3,-1.969968e+10,19272455.0,-1022.167599,TIRT_2023_Q3_FS.xlsx,TIRT_2023_Q3_FS.xlsx,True
7933,LAPD,2021,Q1,-7.992608e+09,8858115.0,-902.292168,LAPD_2021_Q1_FS.xlsx,LAPD_2021_Q1_FS.xlsx,True
13409,TIRT,2023,Q2,-1.325943e+10,19272455.0,-687.999133,TIRT_2023_Q2_FS.xlsx,TIRT_2023_Q2_FS.xlsx,True
5785,HDTX,2023,Q3,-2.108860e+10,31346000.0,-672.768328,HDTX_2023_Q3_FS.xlsx,HDTX_2023_Q3_FS.xlsx,True
13415,TIRT,2024,Q4,-3.924295e+10,72657658.0,-540.107507,TIRT_2024_Q4_FS.xlsx,TIRT_2024_Q4_FS.xlsx,True
13414,TIRT,2024,Q3,-1.837773e+10,64996325.0,-282.750339,TIRT_2024_Q3_FS.xlsx,TIRT_2024_Q3_FS.xlsx,True
4889,ETWA,2020,Q4,-2.664174e+10,467391344.0,-57.000928,ETWA_2020_Q4_FS.xlsx,ETWA_2020_Q4_FS.xlsx,True
4891,ETWA,2021,Q2,-1.463312e+10,340675909.0,-42.953194,ETWA_2021_Q2_FS.xlsx,ETWA_2021_Q2_FS.xlsx,True
4892,ETWA,2021,Q3,-2.165059e+10,521794629.0,-41.492551,ETWA_2021_Q3_FS.xlsx,ETWA_2021_Q3_FS.xlsx,True
9520,MTPS,2022,Q4,-3.348513e+10,918021149.0,-36.475341,MTPS_2022_Q4_FS.xlsx,MTPS_2022_Q4_FS.xlsx,True
13408,TIRT,2022,Q4,-2.721164e+10,925150997.0,-29.413184,TIRT_2022_Q4_FS.xlsx,TIRT_2022_Q4_FS.xlsx,True
667,AMMN,2025,Q1,-5.739000e+07,2124000.0,-27.019774,AMMN_2025_Q1_FS.xlsx,AMMN_2025_Q1_FS.xlsx,True

MOST EXTREME DEBT TO ASSETS

,ticker,year,quarter,total_liabilities,total_assets,debt_to_assets,total_liabilities_source_file,total_assets_source_file,debt_to_assets_same_source
760,ANTM,2023,Q2,1.269258e+13,3.636867e+07,348997.678386,ANTM_2023_Q2_FS.xlsx,ANTM_2023_Q2_FS.xlsx,True
7939,LAPD,2022,Q3,2.623420e+11,6.916923e+07,3792.755752,LAPD_2022_Q3_FS.xlsx,LAPD_2022_Q3_FS.xlsx,True
7938,LAPD,2022,Q2,2.572563e+11,6.999136e+07,3675.544300,LAPD_2022_Q2_FS.xlsx,LAPD_2022_Q2_FS.xlsx,True
2877,BTEL,2020,Q4,1.130682e+13,3.266000e+09,3461.977648,BTEL_2020_Q4_FS.xlsx,BTEL_2020_Q4_FS.xlsx,True
7936,LAPD,2021,Q4,2.488226e+11,7.793900e+07,3192.529504,LAPD_2021_Q4_FS.xlsx,LAPD_2021_Q4_FS.xlsx,True
2878,BTEL,2021,Q1,1.133469e+13,3.817000e+09,2969.528163,BTEL_2021_Q1_FS.xlsx,BTEL_2021_Q1_FS.xlsx,True
7937,LAPD,2022,Q1,2.500337e+11,8.643155e+07,2892.852411,LAPD_2022_Q1_FS.xlsx,LAPD_2022_Q1_FS.xlsx,True
2876,BTEL,2020,Q3,9.672782e+12,4.544000e+09,2128.693222,BTEL_2020_Q3_FS.xlsx,BTEL_2020_Q3_FS.xlsx,True
2879,BTEL,2021,Q2,1.138309e+13,6.811000e+09,1671.279841,BTEL_2021_Q2_FS.xlsx,BTEL_2021_Q2_FS.xlsx,True
2874,BTEL,2020,Q1,1.550545e+13,1.605700e+10,965.650744,BTEL_2020_Q1_FS.xlsx,BTEL_2020_Q1_FS.xlsx,True
2875,BTEL,2020,Q2,1.543377e+13,1.629500e+10,947.147653,BTEL_2020_Q2_FS.xlsx,BTEL_2020_Q2_FS.xlsx,True
2880,BTEL,2021,Q3,1.139880e+13,2.044900e+10,557.425840,BTEL_2021_Q3_FS.xlsx,BTEL_2021_Q3_FS.xlsx,True
2881,BTEL,2021,Q4,5.756644e+12,2.075800e+10,277.321707,BTEL_2021_Q4_FS.xlsx,BTEL_2021_Q4_FS.xlsx,True
5400,GLOB,2025,Q1,1.100003e+12,4.497603e+09,244.575322,GLOB_2025_Q1_FS.xlsx,GLOB_2025_Q1_FS.xlsx,True
7940,LAPD,2022,Q4,1.548994e+10,6.453083e+07,240.039406,LAPD_2022_Q4_FS.xlsx,LAPD_2022_Q4_FS.xlsx,True
7941,LAPD,2023,Q1,1.592909e+10,8.779868e+07,181.427447,LAPD_2023_Q1_FS.xlsx,LAPD_2023_Q1_FS.xlsx,True
2885,BTEL,2022,Q4,5.890102e+12,3.327500e+10,177.012832,BTEL_2022_Q4_FS.xlsx,BTEL_2022_Q4_FS.xlsx,True
2886,BTEL,2023,Q1,5.920714e+12,3.495900e+10,169.361652,BTEL_2023_Q1_FS.xlsx,BTEL_2023_Q1_FS.xlsx,True
2887,BTEL,2023,Q2,5.954107e+12,3.859600e+10,154.267463,BTEL_2023_Q2_FS.xlsx,BTEL_2023_Q2_FS.xlsx,True
5394,GLOB,2023,Q2,9.289811e+11,6.353687e+09,146.211334,GLOB_2023_Q2_FS.xlsx,GLOB_2023_Q2_FS.xlsx,True

MOST EXTREME CASH TO ASSETS

,ticker,year,quarter,cash,total_assets,cash_to_assets,cash_source_file,total_assets_source_file,cash_to_assets_same_source
760,ANTM,2023,Q2,6.581605e+12,3.636867e+07,180969.106758,ANTM_2023_Q2_FS.xlsx,ANTM_2023_Q2_FS.xlsx,True
9976,OASA,2021,Q3,4.714548e+10,4.869313e+10,0.968216,OASA_2021_Q3_FS.xlsx,OASA_2021_Q3_FS.xlsx,True
9970,OASA,2020,Q1,4.790009e+10,4.960400e+10,0.965650,OASA_2020_Q1_FS.xlsx,OASA_2020_Q1_FS.xlsx,True
9973,OASA,2020,Q4,4.511678e+10,4.684005e+10,0.963209,OASA_2020_Q4_FS.xlsx,OASA_2020_Q4_FS.xlsx,True
9971,OASA,2020,Q2,4.568849e+10,4.787057e+10,0.954417,OASA_2020_Q2_FS.xlsx,OASA_2020_Q2_FS.xlsx,True
9972,OASA,2020,Q3,4.557329e+10,4.807902e+10,0.947883,OASA_2020_Q3_FS.xlsx,OASA_2020_Q3_FS.xlsx,True
2985,BUKA,2021,Q3,2.363788e+13,2.501976e+13,0.944768,BUKA_2021_Q3_FS.xlsx,BUKA_2021_Q3_FS.xlsx,True
517,ALKA,2023,Q4,3.161084e+11,3.397438e+11,0.930432,ALKA_2023_Q4_FS.xlsx,ALKA_2023_Q4_FS.xlsx,True
2986,BUKA,2021,Q4,2.470039e+13,2.661555e+13,0.928043,BUKA_2021_Q4_FS.xlsx,BUKA_2021_Q4_FS.xlsx,True
9975,OASA,2021,Q2,4.630111e+10,5.017127e+10,0.922861,OASA_2021_Q2_FS.xlsx,OASA_2021_Q2_FS.xlsx,True
10021,OCAP,2025,Q1,1.255643e+10,1.388021e+10,0.904628,OCAP_2025_Q1_FS.xlsx,OCAP_2025_Q1_FS.xlsx,True
9974,OASA,2021,Q1,4.496397e+10,5.033318e+10,0.893327,OASA_2021_Q1_FS.xlsx,OASA_2021_Q1_FS.xlsx,True
10017,OCAP,2024,Q1,8.036834e+09,9.259089e+09,0.867994,OCAP_2024_Q1_FS.xlsx,OCAP_2024_Q1_FS.xlsx,True
8890,MGNA,2021,Q2,1.334940e+09,1.553097e+09,0.859534,MGNA_2021_Q2_FS.xlsx,MGNA_2021_Q2_FS.xlsx,True
12837,STAR,2022,Q2,4.383811e+11,5.102983e+11,0.859068,STAR_2022_Q2_FS.xlsx,STAR_2022_Q2_FS.xlsx,True
12836,STAR,2022,Q1,4.371626e+11,5.094777e+11,0.858060,STAR_2022_Q1_FS.xlsx,STAR_2022_Q1_FS.xlsx,True
12835,STAR,2021,Q4,4.358108e+11,5.084471e+11,0.857141,STAR_2021_Q4_FS.xlsx,STAR_2021_Q4_FS.xlsx,True
8892,MGNA,2022,Q1,7.954414e+08,9.299798e+08,0.855332,MGNA_2022_Q1_FS.xlsx,MGNA_2022_Q1_FS.xlsx,True
10007,OCAP,2020,Q4,2.067275e+10,2.425848e+10,0.852187,OCAP_2020_Q4_FS.xlsx,OCAP_2020_Q4_FS.xlsx,True
12838,STAR,2022,Q3,4.336978e+11,5.092940e+11,0.851567,STAR_2022_Q3_FS.xlsx,STAR_2022_Q3_FS.xlsx,True

MOST EXTREME OCF TO REVENUE

,ticker,year,quarter,operating_cash_flow,revenue,ocf_to_revenue,operating_cash_flow_source_file,revenue_source_file,ocf_to_revenue_same_source,abs_ocf_to_revenue
5788,HDTX,2024,Q3,-4.193269e+09,538000.0,-7794.180297,HDTX_2024_Q3_FS.xlsx,HDTX_2024_Q3_FS.xlsx,True,7794.180297
5789,HDTX,2024,Q4,-3.566482e+09,538000.0,-6629.148699,HDTX_2024_Q4_FS.xlsx,HDTX_2024_Q4_FS.xlsx,True,6629.148699
5787,HDTX,2024,Q1,3.790790e+08,538000.0,704.607807,HDTX_2024_Q1_FS.xlsx,HDTX_2024_Q1_FS.xlsx,True,704.607807
7934,LAPD,2021,Q2,-5.565587e+09,8858115.0,-628.303778,LAPD_2021_Q2_FS.xlsx,LAPD_2021_Q2_FS.xlsx,True,628.303778
13411,TIRT,2023,Q4,-1.216603e+10,22360023.0,-544.097520,TIRT_2023_Q4_FS.xlsx,TIRT_2023_Q4_FS.xlsx,True,544.097520
13410,TIRT,2023,Q3,-9.819694e+09,19272455.0,-509.519622,TIRT_2023_Q3_FS.xlsx,TIRT_2023_Q3_FS.xlsx,True,509.519622
10419,PGJO,2021,Q2,-3.600524e+09,7104300.0,-506.809064,PGJO_2021_Q2_FS.xlsx,PGJO_2021_Q2_FS.xlsx,True,506.809064
7933,LAPD,2021,Q1,-3.705881e+09,8858115.0,-418.359958,LAPD_2021_Q1_FS.xlsx,LAPD_2021_Q1_FS.xlsx,True,418.359958
13409,TIRT,2023,Q2,-6.889642e+09,19272455.0,-357.486477,TIRT_2023_Q2_FS.xlsx,TIRT_2023_Q2_FS.xlsx,True,357.486477
10418,PGJO,2021,Q1,-1.432002e+09,4768500.0,-300.304464,PGJO_2021_Q1_FS.xlsx,PGJO_2021_Q1_FS.xlsx,True,300.304464
5783,HDTX,2023,Q1,-1.590927e+09,5402000.0,-294.507034,HDTX_2023_Q1_FS.xlsx,HDTX_2023_Q1_FS.xlsx,True,294.507034
5786,HDTX,2023,Q4,8.007694e+09,27908000.0,286.931847,HDTX_2023_Q4_FS.xlsx,HDTX_2023_Q4_FS.xlsx,True,286.931847
8241,LPPS,2020,Q3,-4.190450e+09,15000000.0,-279.363319,LPPS_2020_Q3_FS.xlsx,LPPS_2020_Q3_FS.xlsx,True,279.363319
5784,HDTX,2023,Q2,-3.119201e+09,13241000.0,-235.571407,HDTX_2023_Q2_FS.xlsx,HDTX_2023_Q2_FS.xlsx,True,235.571407
5785,HDTX,2023,Q3,5.286208e+09,31346000.0,168.640592,HDTX_2023_Q3_FS.xlsx,HDTX_2023_Q3_FS.xlsx,True,168.640592
667,AMMN,2025,Q1,-2.821730e+08,2124000.0,-132.849812,AMMN_2025_Q1_FS.xlsx,AMMN_2025_Q1_FS.xlsx,True,132.849812
12672,SQMI,2024,Q2,-1.635668e+10,136115391.0,-120.167758,SQMI_2024_Q2_FS.xlsx,SQMI_2024_Q2_FS.xlsx,True,120.167758
13415,TIRT,2024,Q4,-8.440387e+09,72657658.0,-116.166514,TIRT_2024_Q4_FS.xlsx,TIRT_2024_Q4_FS.xlsx,True,116.166514
6569,INDX,2025,Q1,-3.293439e+09,30973966.0,-106.329254,INDX_2025_Q1_FS.xlsx,INDX_2025_Q1_FS.xlsx,True,106.329254
8242,LPPS,2020,Q4,-6.227435e+09,60000000.0,-103.790578,LPPS_2020_Q4_FS.xlsx,LPPS_2020_Q4_FS.xlsx,True,103.790578

In [9]:
# CELL 9 - AUDIT EXTREME RATIO CASES WITH NORMALIZATION DETAILS

extreme_files = [
    "ANTM_2023_Q2_FS.xlsx",
    "HDTX_2024_Q4_FS.xlsx",
    "LAPD_2022_Q3_FS.xlsx",
]

extreme_detail_df = (
    idx_normalized_df[
        idx_normalized_df[
            "source_file"
        ].isin(extreme_files)
    ]
    [
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "selected_value",
            "normalized_value",
            "currency",
            "unit_scale",
            "multiplier",
            "effective_multiplier",
            "final_scale_mode",
            "source_file",
            "source_sheet",
            "source_label",
            "currency_scale_status"
        ]
    ]
    .copy()
)


print("EXTREME FILE DETAIL")

display(
    extreme_detail_df
    .sort_values(
        [
            "ticker",
            "year",
            "quarter",
            "metric"
        ]
    )
)

EXTREME FILE DETAIL

,ticker,year,quarter,metric,selected_value,normalized_value,currency,unit_scale,multiplier,effective_multiplier,final_scale_mode,source_file,source_sheet,source_label,currency_scale_status
4175,ANTM,2023,Q2,cash,6.581605e+06,6.581605e+12,IDR,MILLION,1000000.0,1000000.0,PRESENTATION_SCALED,ANTM_2023_Q2_FS.xlsx,1210000,Kas dan setara kas,FOUND
4176,ANTM,2023,Q2,gross_profit,4.240811e+06,4.240811e+12,IDR,MILLION,1000000.0,1000000.0,PRESENTATION_SCALED,ANTM_2023_Q2_FS.xlsx,1311000,Jumlah laba bruto,FOUND
4177,ANTM,2023,Q2,operating_cash_flow,1.691955e+06,1.691955e+12,IDR,MILLION,1000000.0,1000000.0,PRESENTATION_SCALED,ANTM_2023_Q2_FS.xlsx,1510000,Total net cash flows received from (used in) o...,FOUND
4178,ANTM,2023,Q2,revenue,2.166111e+07,2.166111e+13,IDR,MILLION,1000000.0,1000000.0,PRESENTATION_SCALED,ANTM_2023_Q2_FS.xlsx,1311000,Sales and revenue,FOUND
4179,ANTM,2023,Q2,total_assets,3.636867e+01,3.636867e+07,IDR,MILLION,1000000.0,1000000.0,PRESENTATION_SCALED,ANTM_2023_Q2_FS.xlsx,1210000,Jumlah aset,FOUND
4180,ANTM,2023,Q2,total_liabilities,1.269258e+07,1.269258e+13,IDR,MILLION,1000000.0,1000000.0,PRESENTATION_SCALED,ANTM_2023_Q2_FS.xlsx,1210000,Jumlah liabilitas,FOUND
31683,HDTX,2024,Q4,cash,2.448360e+05,2.448360e+08,IDR,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,HDTX_2024_Q4_FS.xlsx,1210000,Kas dan setara kas,FOUND
31684,HDTX,2024,Q4,gross_profit,-3.071064e+07,-3.071064e+10,IDR,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,HDTX_2024_Q4_FS.xlsx,1311000,Jumlah laba bruto,FOUND
31685,HDTX,2024,Q4,operating_cash_flow,-3.566482e+06,-3.566482e+09,IDR,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,HDTX_2024_Q4_FS.xlsx,1510000,Total net cash flows received from (used in) o...,FOUND
31686,HDTX,2024,Q4,revenue,5.380000e+02,5.380000e+05,IDR,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,HDTX_2024_Q4_FS.xlsx,1311000,Sales and revenue,FOUND
31687,HDTX,2024,Q4,total_assets,2.138769e+08,2.138769e+11,IDR,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,HDTX_2024_Q4_FS.xlsx,1210000,Jumlah aset,FOUND
31688,HDTX,2024,Q4,total_liabilities,3.345901e+08,3.345901e+11,IDR,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,HDTX_2024_Q4_FS.xlsx,1210000,Jumlah liabilitas,FOUND
44381,LAPD,2022,Q3,cash,4.119173e+07,4.119173e+07,IDR,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2022_Q3_FS.xlsx,3210000,Kas dan setara kas,FOUND
44382,LAPD,2022,Q3,gross_profit,0.000000e+00,0.000000e+00,IDR,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2022_Q3_FS.xlsx,3311000,Jumlah laba bruto,FOUND
44383,LAPD,2022,Q3,operating_cash_flow,-1.146777e+09,-1.146777e+09,IDR,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2022_Q3_FS.xlsx,3510000,Total net cash flows received from (used in) o...,FOUND
44384,LAPD,2022,Q3,revenue,0.000000e+00,0.000000e+00,IDR,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2022_Q3_FS.xlsx,3311000,Sales and revenue,FOUND
44385,LAPD,2022,Q3,total_assets,6.916923e+07,6.916923e+07,IDR,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2022_Q3_FS.xlsx,3210000,Jumlah aset,FOUND
44386,LAPD,2022,Q3,total_liabilities,2.623420e+11,2.623420e+11,IDR,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2022_Q3_FS.xlsx,3210000,Jumlah liabilitas,FOUND

In [11]:
# CELL 10 - COMPARE EXTREME FILES WITH NEIGHBOR PERIODS

extreme_tickers = (
    extreme_detail_df[
        "ticker"
    ]
    .dropna()
    .unique()
)


neighbor_audit_df = (
    idx_normalized_df[
        idx_normalized_df[
            "ticker"
        ].isin(
            extreme_tickers
        )
    ]
    [
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "selected_value",
            "normalized_value",
            "currency",
            "unit_scale",
            "multiplier",
            "effective_multiplier",
            "final_scale_mode",
            "source_file"
        ]
    ]
    .copy()
)


quarter_order = {
    "Q1": 1,
    "Q2": 2,
    "Q3": 3,
    "Q4": 4
}


neighbor_audit_df[
    "quarter_order"
] = (
    neighbor_audit_df[
        "quarter"
    ].map(
        quarter_order
    )
)


neighbor_audit_df = (
    neighbor_audit_df
    .sort_values(
        [
            "ticker",
            "metric",
            "year",
            "quarter_order"
        ]
    )
)


display(
    neighbor_audit_df[
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "selected_value",
            "normalized_value",
            "unit_scale",
            "multiplier",
            "effective_multiplier",
            "final_scale_mode",
            "source_file"
        ]
    ]
)

,ticker,year,quarter,metric,selected_value,normalized_value,unit_scale,multiplier,effective_multiplier,final_scale_mode,source_file
4097,ANTM,2020,Q1,cash,3.160647e+09,3.160647e+12,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,ANTM_2020_Q1_FS.xlsx
4103,ANTM,2020,Q2,cash,3.006270e+09,3.006270e+12,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,ANTM_2020_Q2_FS.xlsx
4109,ANTM,2020,Q3,cash,3.669383e+09,3.669383e+12,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,ANTM_2020_Q3_FS.xlsx
4115,ANTM,2020,Q4,cash,3.984388e+09,3.984388e+12,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,ANTM_2020_Q4_FS.xlsx
4121,ANTM,2021,Q1,cash,5.326122e+09,5.326122e+12,THOUSAND,1000.0,1000.0,PRESENTATION_SCALED,ANTM_2021_Q1_FS.xlsx
...,...,...,...,...,...,...,...,...,...,...,...
44412,LAPD,2023,Q4,total_liabilities,1.599281e+11,1.599281e+11,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2023_Q4_FS.xlsx
44418,LAPD,2024,Q1,total_liabilities,1.533519e+11,1.533519e+11,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2024_Q1_FS.xlsx
44424,LAPD,2024,Q2,total_liabilities,1.868606e+11,1.868606e+11,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2024_Q2_FS.xlsx
44430,LAPD,2024,Q4,total_liabilities,1.967051e+11,1.967051e+11,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2024_Q4_FS.xlsx
44436,LAPD,2025,Q1,total_liabilities,1.826380e+11,1.826380e+11,UNIT,1.0,1.0,PRESENTATION_SCALED,LAPD_2025_Q1_FS.xlsx

In [12]:
# CELL 11 - REBUILD RATIOS FOR EXTREME TICKERS ACROSS PERIODS

extreme_ticker_wide_df = (
    neighbor_audit_df
    .pivot_table(
        index=[
            "ticker",
            "year",
            "quarter"
        ],
        columns="metric",
        values="normalized_value",
        aggfunc="first"
    )
    .reset_index()
)

extreme_ticker_wide_df.columns.name = None


extreme_ticker_wide_df[
    "gross_margin"
] = safe_divide(
    extreme_ticker_wide_df.get(
        "gross_profit"
    ),
    extreme_ticker_wide_df.get(
        "revenue"
    )
)


extreme_ticker_wide_df[
    "debt_to_assets"
] = safe_divide(
    extreme_ticker_wide_df.get(
        "total_liabilities"
    ),
    extreme_ticker_wide_df.get(
        "total_assets"
    )
)


extreme_ticker_wide_df[
    "cash_to_assets"
] = safe_divide(
    extreme_ticker_wide_df.get(
        "cash"
    ),
    extreme_ticker_wide_df.get(
        "total_assets"
    )
)


extreme_ticker_wide_df[
    "ocf_to_revenue"
] = safe_divide(
    extreme_ticker_wide_df.get(
        "operating_cash_flow"
    ),
    extreme_ticker_wide_df.get(
        "revenue"
    )
)


display(
    extreme_ticker_wide_df[
        [
            "ticker",
            "year",
            "quarter",
            "gross_margin",
            "debt_to_assets",
            "cash_to_assets",
            "ocf_to_revenue"
        ]
    ]
    .sort_values(
        [
            "ticker",
            "year",
            "quarter"
        ]
    )
)

,ticker,year,quarter,gross_margin,debt_to_assets,cash_to_assets,ocf_to_revenue
0,ANTM,2020,Q1,0.107989,0.414221,0.102715,0.003626
1,ANTM,2020,Q2,0.141885,0.397213,0.100098,0.013624
2,ANTM,2020,Q3,0.161024,0.388870,0.118466,0.061955
3,ANTM,2020,Q4,0.163514,0.399945,0.125574,0.081055
4,ANTM,2021,Q1,0.176486,0.394335,0.162924,0.204138
5,ANTM,2021,Q2,0.183422,0.385716,0.158621,0.139130
6,ANTM,2021,Q3,0.194026,0.389088,0.191220,0.168123
7,ANTM,2021,Q4,0.165404,0.366964,0.154610,0.131164
8,ANTM,2022,Q1,0.251126,0.292824,0.131884,0.049396
9,ANTM,2022,Q2,0.214644,0.334337,0.100249,0.045881
10,ANTM,2022,Q3,0.177748,0.332141,0.136591,0.061146
11,ANTM,2022,Q4,0.178760,0.295066,0.133081,0.089441
12,ANTM,2023,Q1,0.245814,0.274852,0.141513,0.034979
13,ANTM,2023,Q2,0.195780,348997.678386,180969.106758,0.078110
14,ANTM,2023,Q3,0.197338,0.306573,0.212403,0.128913
15,ANTM,2023,Q4,0.153838,0.272702,0.214901,0.106152
16,ANTM,2024,Q1,0.029086,0.237331,0.287696,-0.166869
17,ANTM,2024,Q2,0.086396,0.242209,0.223357,-0.055846
18,ANTM,2024,Q3,0.094979,0.258732,0.234167,-0.003994
19,ANTM,2025,Q1,0.139051,0.283207,0.143176,0.079614
20,HDTX,2020,Q1,-3.283309,0.907867,0.001006,-2.768010
21,HDTX,2020,Q2,-4.064281,0.890407,0.000310,-3.098085
22,HDTX,2020,Q3,-4.556508,0.934508,0.001349,-1.753284
23,HDTX,2020,Q4,-4.049546,0.945366,0.002106,0.567334
24,HDTX,2021,Q1,-2.214107,0.981416,0.000634,-2.358173
25,HDTX,2021,Q2,-3.098672,1.018314,0.000748,-1.564185
26,HDTX,2021,Q3,-3.326156,1.029211,0.001639,-1.223633
27,HDTX,2021,Q4,-3.476145,1.058989,0.001377,-0.398703
28,HDTX,2022,Q1,-2.149567,1.081472,0.001476,-0.451245
29,HDTX,2022,Q2,-3.142368,1.128701,0.001192,-1.367571
30,HDTX,2022,Q3,-4.718030,1.280129,0.003017,-1.625915
31,HDTX,2022,Q4,-5.412920,1.292753,0.002678,-0.407622
32,HDTX,2023,Q1,-1267.794335,1.299367,0.005786,-294.507034
33,HDTX,2023,Q2,-1060.340080,1.324175,0.001920,-235.571407
34,HDTX,2023,Q3,-672.768328,1.329795,0.000822,168.640592
35,HDTX,2023,Q4,-1056.352157,1.387704,0.002843,286.931847
36,HDTX,2024,Q1,-11274.695167,1.435427,0.007522,704.607807
37,HDTX,2024,Q3,-34097.706320,1.473483,0.000540,-7794.180297
38,HDTX,2024,Q4,-57082.968401,1.564405,0.001145,-6629.148699
39,HDTX,2025,Q1,NaN,1.615648,0.001153,NaN
40,LAPD,2020,Q1,NaN,1.842972,0.005975,NaN
41,LAPD,2020,Q2,-5.437310,1.801077,0.004365,-1.029470
42,LAPD,2020,Q3,-4.835990,1.959205,0.015107,-0.697509
43,LAPD,2020,Q4,-2.748990,2.179541,0.004706,-0.344118
44,LAPD,2021,Q1,-902.292168,2.381747,0.004166,-418.359958
45,LAPD,2021,Q2,-1796.392377,2.571524,0.003332,-628.303778
46,LAPD,2021,Q3,NaN,2.769235,0.001201,NaN
47,LAPD,2021,Q4,NaN,3192.529504,0.641027,NaN
48,LAPD,2022,Q1,NaN,2892.852411,0.676305,NaN
49,LAPD,2022,Q2,NaN,3675.544300,0.600272,NaN
50,LAPD,2022,Q3,NaN,3792.755752,0.595521,NaN
51,LAPD,2022,Q4,NaN,240.039406,0.566448,NaN
52,LAPD,2023,Q1,NaN,181.427447,0.487313,NaN
53,LAPD,2023,Q2,NaN,0.745145,0.146270,NaN
54,LAPD,2023,Q3,0.066944,0.739812,0.154456,-0.453475
55,LAPD,2023,Q4,0.018564,0.785501,0.149900,0.056822
56,LAPD,2024,Q1,-0.023218,0.794506,0.175529,0.320337
57,LAPD,2024,Q2,0.033378,0.826105,0.174137,0.018379
58,LAPD,2024,Q4,0.046346,0.874052,0.129961,-0.097274
59,LAPD,2025,Q1,0.072871,0.861700,0.077802,-0.042285

In [13]:
# CELL 12 - INSPECT RAW WORKBOOK CONTEXT FOR SUSPICIOUS RATIO COMPONENTS

from openpyxl import load_workbook


suspicious_cases = [
    {
        "source_file": "ANTM_2023_Q2_FS.xlsx",
        "metrics": [
            "total_assets",
            "total_liabilities",
            "cash"
        ]
    },
    {
        "source_file": "HDTX_2024_Q4_FS.xlsx",
        "metrics": [
            "revenue",
            "gross_profit"
        ]
    },
    {
        "source_file": "LAPD_2022_Q3_FS.xlsx",
        "metrics": [
            "total_assets",
            "total_liabilities"
        ]
    }
]


audit_rows = []


for case in suspicious_cases:

    source_file = case["source_file"]

    case_rows = (
        idx_normalized_df[
            (
                idx_normalized_df["source_file"]
                == source_file
            )
            &
            (
                idx_normalized_df["metric"]
                .isin(case["metrics"])
            )
        ]
        .copy()
    )


    for _, metric_row in case_rows.iterrows():

        wb = None

        try:

            wb = load_workbook(
                _relocated_idx_path(metric_row["source_path"]),
                read_only=True,
                data_only=True
            )

            sheet_name = str(
                metric_row["source_sheet"]
            )

            if sheet_name not in wb.sheetnames:

                audit_rows.append(
                    {
                        "source_file": source_file,
                        "metric": metric_row["metric"],
                        "source_label":
                            metric_row["source_label"],
                        "selected_value":
                            metric_row["selected_value"],
                        "normalized_value":
                            metric_row["normalized_value"],
                        "status": "SHEET_NOT_FOUND",
                        "matches": []
                    }
                )

                continue


            ws = wb[sheet_name]

            target_label = (
                str(metric_row["source_label"])
                .strip()
                .lower()
            )

            matches = []


            for row in ws.iter_rows(
                min_row=1,
                max_row=min(ws.max_row, 300),
                min_col=1,
                max_col=min(ws.max_column, 20),
                values_only=False
            ):

                for cell in row:

                    if cell.value is None:
                        continue

                    cell_text = (
                        str(cell.value)
                        .strip()
                        .lower()
                    )


                    if cell_text == target_label:

                        nearby = []

                        start_col = max(
                            1,
                            cell.column - 1
                        )

                        end_col = min(
                            ws.max_column,
                            cell.column + 6
                        )


                        for col_idx in range(
                            start_col,
                            end_col + 1
                        ):

                            nearby_cell = ws.cell(
                                row=cell.row,
                                column=col_idx
                            )

                            nearby.append(
                                {
                                    "coordinate":
                                        nearby_cell.coordinate,

                                    "value":
                                        nearby_cell.value
                                }
                            )


                        matches.append(
                            {
                                "label_coordinate":
                                    cell.coordinate,

                                "nearby_values":
                                    nearby
                            }
                        )


            audit_rows.append(
                {
                    "source_file":
                        source_file,

                    "ticker":
                        metric_row["ticker"],

                    "year":
                        metric_row["year"],

                    "quarter":
                        metric_row["quarter"],

                    "metric":
                        metric_row["metric"],

                    "source_sheet":
                        sheet_name,

                    "source_label":
                        metric_row["source_label"],

                    "selected_value":
                        metric_row["selected_value"],

                    "normalized_value":
                        metric_row["normalized_value"],

                    "unit_scale":
                        metric_row["unit_scale"],

                    "multiplier":
                        metric_row["multiplier"],

                    "status":
                        (
                            "FOUND_LABEL"
                            if matches
                            else "LABEL_NOT_FOUND"
                        ),

                    "matches":
                        matches
                }
            )


        except Exception as e:

            audit_rows.append(
                {
                    "source_file":
                        source_file,

                    "metric":
                        metric_row["metric"],

                    "source_label":
                        metric_row["source_label"],

                    "selected_value":
                        metric_row["selected_value"],

                    "normalized_value":
                        metric_row["normalized_value"],

                    "status":
                        f"READ_ERROR:{type(e).__name__}",

                    "matches": []
                }
            )


        finally:

            if wb is not None:
                wb.close()


suspicious_workbook_audit_df = pd.DataFrame(
    audit_rows
)


print("AUDIT STATUS")

print(
    suspicious_workbook_audit_df[
        "status"
    ].value_counts(
        dropna=False
    )
)


for _, row in (
    suspicious_workbook_audit_df
    .sort_values(
        [
            "source_file",
            "metric"
        ]
    )
    .iterrows()
):

    print("\n" + "=" * 120)

    print(
        row["source_file"],
        "|",
        row["metric"]
    )

    print(
        "Selected:",
        row["selected_value"],
        "| Normalized:",
        row["normalized_value"]
    )

    print(
        "Label:",
        row["source_label"]
    )

    print(
        "Unit:",
        row.get("unit_scale"),
        "| Multiplier:",
        row.get("multiplier")
    )

    print(
        "Workbook matches:"
    )

    print(
        row["matches"]
    )

AUDIT STATUS
status
FOUND_LABEL    7
Name: count, dtype: int64

========================================================================================================================
ANTM_2023_Q2_FS.xlsx | cash
Selected: 6581605.0 | Normalized: 6581605000000.0
Label: Kas dan setara kas
Unit: MILLION | Multiplier: 1000000.0
Workbook matches:
[{'label_coordinate': 'A7', 'nearby_values': [{'coordinate': 'A7', 'value': 'Kas dan setara kas'}, {'coordinate': 'B7', 'value': 6581605.0}, {'coordinate': 'C7', 'value': 4476491.0}, {'coordinate': 'D7', 'value': 'Cash and cash equivalents'}]}]

========================================================================================================================
ANTM_2023_Q2_FS.xlsx | total_assets
Selected: 36.368666 | Normalized: 36368666.0
Label: Jumlah aset
Unit: MILLION | Multiplier: 1000000.0
Workbook matches:
[{'label_coordinate': 'A127', 'nearby_values': [{'coordinate': 'A127', 'value': 'Jumlah aset'}, {'coordinate': 'B127', 'value': 36.368666}, {'coordinate': 'C127', 'value': 33637271.0}, {'coordinate': 'D127', 'value': 'Total assets'}]}]

========================================================================================================================
ANTM_2023_Q2_FS.xlsx | total_liabilities
Selected: 12692580.0 | Normalized: 12692580000000.0
Label: Jumlah liabilitas
Unit: MILLION | Multiplier: 1000000.0
Workbook matches:
[{'label_coordinate': 'A246', 'nearby_values': [{'coordinate': 'A246', 'value': 'Jumlah liabilitas'}, {'coordinate': 'B246', 'value': 12692580.0}, {'coordinate': 'C246', 'value': 9925211.0}, {'coordinate': 'D246', 'value': 'Total liabilities'}]}]

========================================================================================================================
HDTX_2024_Q4_FS.xlsx | gross_profit
Selected: -30710637.0 | Normalized: -30710637000.0
Label: Jumlah laba bruto
Unit: THOUSAND | Multiplier: 1000.0
Workbook matches:
[{'label_coordinate': 'A8', 'nearby_values': [{'coordinate': 'A8', 'value': 'Jumlah laba bruto'}, {'coordinate': 'B8', 'value': -30710637}, {'coordinate': 'C8', 'value': -29480676}, {'coordinate': 'D8', 'value': 'Total gross profit'}]}]

========================================================================================================================
HDTX_2024_Q4_FS.xlsx | revenue
Selected: 538.0 | Normalized: 538000.0
Label: Sales and revenue
Unit: THOUSAND | Multiplier: 1000.0
Workbook matches:
[{'label_coordinate': 'D6', 'nearby_values': [{'coordinate': 'C6', 'value': 27908}, {'coordinate': 'D6', 'value': 'Sales and revenue'}]}]

========================================================================================================================
LAPD_2022_Q3_FS.xlsx | total_assets
Selected: 69169231.0 | Normalized: 69169231.0
Label: Jumlah aset
Unit: UNIT | Multiplier: 1.0
Workbook matches:
[{'label_coordinate': 'A70', 'nearby_values': [{'coordinate': 'A70', 'value': 'Jumlah aset'}, {'coordinate': 'B70', 'value': 69169231.0}, {'coordinate': 'C70', 'value': 77939737.0}, {'coordinate': 'D70', 'value': 'Total assets'}, {'coordinate': 'E70', 'value': None}, {'coordinate': 'F70', 'value': None}]}]

========================================================================================================================
LAPD_2022_Q3_FS.xlsx | total_liabilities
Selected: 262341998765.0 | Normalized: 262341998765.0
Label: Jumlah liabilitas
Unit: UNIT | Multiplier: 1.0
Workbook matches:
[{'label_coordinate': 'A152', 'nearby_values': [{'coordinate': 'A152', 'value': 'Jumlah liabilitas'}, {'coordinate': 'B152', 'value': 262341998765.0}, {'coordinate': 'C152', 'value': 248715057382.0}, {'coordinate': 'D152', 'value': 'Total liabilities'}, {'coordinate': 'E152', 'value': None}, {'coordinate': 'F152', 'value': None}]}]

In [14]:
# CELL 13 - PRECISE CELL AUDIT FOR SUSPICIOUS BENCHMARK VALUES

from openpyxl import load_workbook


precise_checks = [
    {
        "source_file": "ANTM_2023_Q2_FS.xlsx",
        "sheet": "1210000",
        "cells": ["B127", "C127"],
        "description": "ANTM total assets"
    },
    {
        "source_file": "LAPD_2022_Q3_FS.xlsx",
        "sheet": "3210000",
        "cells": ["B70", "C70", "B152", "C152"],
        "description": "LAPD assets and liabilities"
    },
    {
        "source_file": "HDTX_2024_Q4_FS.xlsx",
        "sheet": "1311000",
        "cells": ["A6", "B6", "C6", "D6", "A8", "B8", "C8", "D8"],
        "description": "HDTX revenue and gross profit"
    }
]


for check in precise_checks:

    source_file = check["source_file"]

    source_path = (
        idx_normalized_df.loc[
            idx_normalized_df["source_file"] == source_file,
            "source_path"
        ]
        .iloc[0]
    )

    print("\n" + "=" * 120)
    print(source_file)
    print(check["description"])

    # data_only=True -> value displayed/calculated by workbook
    wb_values = load_workbook(
        _relocated_idx_path(source_path),
        read_only=False,
        data_only=True
    )

    # data_only=False -> formula/raw workbook content
    wb_raw = load_workbook(
        _relocated_idx_path(source_path),
        read_only=False,
        data_only=False
    )

    try:

        ws_values = wb_values[check["sheet"]]
        ws_raw = wb_raw[check["sheet"]]

        for coordinate in check["cells"]:

            value_cell = ws_values[coordinate]
            raw_cell = ws_raw[coordinate]

            print(
                coordinate,
                "| value:",
                repr(value_cell.value),
                "| raw/formula:",
                repr(raw_cell.value),
                "| number_format:",
                repr(value_cell.number_format)
            )

    finally:

        wb_values.close()
        wb_raw.close()

========================================================================================================================
ANTM_2023_Q2_FS.xlsx
ANTM total assets
B127 | value: 36.368666 | raw/formula: 36.368666 | number_format: '#,##0;(#,##0)'
C127 | value: 33637271.0 | raw/formula: 33637271.0 | number_format: '#,##0;(#,##0)'

========================================================================================================================
LAPD_2022_Q3_FS.xlsx
LAPD assets and liabilities
B70 | value: 69169231.0 | raw/formula: 69169231.0 | number_format: '#,##0;\\(#,##0\\)'
C70 | value: 77939737.0 | raw/formula: 77939737.0 | number_format: '#,##0;\\(#,##0\\)'
B152 | value: 262341998765.0 | raw/formula: 262341998765.0 | number_format: '#,##0;\\(#,##0\\)'
C152 | value: 248715057382.0 | raw/formula: 248715057382.0 | number_format: '#,##0;\\(#,##0\\)'

========================================================================================================================
HDTX_2024_Q4_FS.xlsx
HDTX revenue and gross profit

e:\BINUS_CODING\Ai Builders Hackhaton\AI-Builders-Hackhaton-2026-Backend\venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

A6 | value: 'Penjualan dan pendapatan usaha' | raw/formula: 'Penjualan dan pendapatan usaha' | number_format: 'General'
B6 | value: 538 | raw/formula: 538 | number_format: '#,##0;\\(#,##0\\)'
C6 | value: 27908 | raw/formula: 27908 | number_format: '#,##0;\\(#,##0\\)'
D6 | value: 'Sales and revenue' | raw/formula: 'Sales and revenue' | number_format: 'General'
A8 | value: 'Jumlah laba bruto' | raw/formula: 'Jumlah laba bruto' | number_format: 'General'
B8 | value: -30710637 | raw/formula: -30710637 | number_format: '#,##0;\\(#,##0\\)'
C8 | value: -29480676 | raw/formula: -29480676 | number_format: '#,##0;\\(#,##0\\)'
D8 | value: 'Total gross profit' | raw/formula: 'Total gross profit' | number_format: 'General'

In [15]:
# CELL 14 - COMPARE SUSPICIOUS COMPONENTS ACROSS NEIGHBOR PERIODS

component_checks = {
    "ANTM": [
        "total_assets",
        "total_liabilities",
        "cash"
    ],

    "LAPD": [
        "total_assets",
        "total_liabilities",
        "cash"
    ],

    "HDTX": [
        "revenue",
        "gross_profit"
    ]
}


component_audit_rows = []


for ticker, metrics in component_checks.items():

    subset = (
        idx_normalized_df[
            (idx_normalized_df["ticker"] == ticker)
            &
            (idx_normalized_df["metric"].isin(metrics))
        ]
        .copy()
    )

    subset["quarter_order"] = subset["quarter"].map(
        {
            "Q1": 1,
            "Q2": 2,
            "Q3": 3,
            "Q4": 4
        }
    )

    subset = subset.sort_values(
        [
            "metric",
            "year",
            "quarter_order"
        ]
    )

    component_audit_rows.append(subset)


suspicious_component_history_df = pd.concat(
    component_audit_rows,
    ignore_index=True
)


display(
    suspicious_component_history_df[
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "selected_value",
            "normalized_value",
            "unit_scale",
            "effective_multiplier",
            "source_file"
        ]
    ]
)

,ticker,year,quarter,metric,selected_value,normalized_value,unit_scale,effective_multiplier,source_file
0,ANTM,2020,Q1,cash,3.160647e+09,3.160647e+12,THOUSAND,1000.0,ANTM_2020_Q1_FS.xlsx
1,ANTM,2020,Q2,cash,3.006270e+09,3.006270e+12,THOUSAND,1000.0,ANTM_2020_Q2_FS.xlsx
2,ANTM,2020,Q3,cash,3.669383e+09,3.669383e+12,THOUSAND,1000.0,ANTM_2020_Q3_FS.xlsx
3,ANTM,2020,Q4,cash,3.984388e+09,3.984388e+12,THOUSAND,1000.0,ANTM_2020_Q4_FS.xlsx
4,ANTM,2021,Q1,cash,5.326122e+09,5.326122e+12,THOUSAND,1000.0,ANTM_2021_Q1_FS.xlsx
...,...,...,...,...,...,...,...,...,...
155,HDTX,2023,Q4,revenue,2.790800e+04,2.790800e+07,THOUSAND,1000.0,HDTX_2023_Q4_FS.xlsx
156,HDTX,2024,Q1,revenue,5.380000e+02,5.380000e+05,THOUSAND,1000.0,HDTX_2024_Q1_FS.xlsx
157,HDTX,2024,Q3,revenue,5.380000e+02,5.380000e+05,THOUSAND,1000.0,HDTX_2024_Q3_FS.xlsx
158,HDTX,2024,Q4,revenue,5.380000e+02,5.380000e+05,THOUSAND,1000.0,HDTX_2024_Q4_FS.xlsx
159,HDTX,2025,Q1,revenue,0.000000e+00,0.000000e+00,THOUSAND,1000.0,HDTX_2025_Q1_FS.xlsx

In [16]:
# CELL 15 - GLOBAL TEMPORAL ANOMALY SCAN FOR NORMALIZED METRICS

global_metric_audit_df = (
    idx_normalized_df[
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "normalized_value",
            "source_file"
        ]
    ]
    .copy()
)


quarter_order = {
    "Q1": 1,
    "Q2": 2,
    "Q3": 3,
    "Q4": 4
}


global_metric_audit_df[
    "quarter_order"
] = (
    global_metric_audit_df[
        "quarter"
    ].map(quarter_order)
)


global_metric_audit_df = (
    global_metric_audit_df
    .sort_values(
        [
            "ticker",
            "metric",
            "year",
            "quarter_order"
        ]
    )
    .reset_index(drop=True)
)


# Absolute magnitude in log space.
# +1 avoids problems when value = 0.
global_metric_audit_df[
    "log_abs_value"
] = np.log10(
    global_metric_audit_df[
        "normalized_value"
    ].abs() + 1
)


global_metric_audit_df[
    "previous_log_abs_value"
] = (
    global_metric_audit_df
    .groupby(
        [
            "ticker",
            "metric"
        ]
    )[
        "log_abs_value"
    ]
    .shift(1)
)


global_metric_audit_df[
    "log_change_from_previous"
] = (
    global_metric_audit_df[
        "log_abs_value"
    ]
    -
    global_metric_audit_df[
        "previous_log_abs_value"
    ]
)


global_metric_audit_df[
    "abs_log_change"
] = (
    global_metric_audit_df[
        "log_change_from_previous"
    ].abs()
)


print(
    "Metric rows:",
    len(global_metric_audit_df)
)

print(
    "Rows with temporal comparison:",
    global_metric_audit_df[
        "abs_log_change"
    ].notna().sum()
)


print("\nTEMPORAL CHANGE SUMMARY")

print(
    global_metric_audit_df[
        "abs_log_change"
    ].describe(
        percentiles=[
            0.90,
            0.95,
            0.99,
            0.995,
            0.999
        ]
    )
)

Metric rows: 83442
Rows with temporal comparison: 78139

TEMPORAL CHANGE SUMMARY
count    78139.000000
mean         0.233615
std          0.382422
min          0.000000
90%          0.600754
95%          0.801132
99%          1.530549
99.5%        1.950786
99.9%        4.155754
max         11.328295
Name: abs_log_change, dtype: float64

In [17]:
# CELL 16 - FLAG GLOBAL EXTREME TEMPORAL CHANGES

temporal_threshold = (
    global_metric_audit_df[
        "abs_log_change"
    ]
    .quantile(0.995)
)


global_metric_audit_df[
    "temporal_anomaly"
] = (
    global_metric_audit_df[
        "abs_log_change"
    ]
    >= temporal_threshold
)


print(
    "99.5% temporal anomaly threshold:",
    temporal_threshold
)

print(
    "Flagged metric rows:",
    global_metric_audit_df[
        "temporal_anomaly"
    ].sum()
)

print(
    "Affected source files:",
    global_metric_audit_df.loc[
        global_metric_audit_df[
            "temporal_anomaly"
        ],
        "source_file"
    ].nunique()
)

print(
    "Affected tickers:",
    global_metric_audit_df.loc[
        global_metric_audit_df[
            "temporal_anomaly"
        ],
        "ticker"
    ].nunique()
)


display(
    global_metric_audit_df[
        global_metric_audit_df[
            "temporal_anomaly"
        ]
    ][
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "normalized_value",
            "log_change_from_previous",
            "abs_log_change",
            "source_file"
        ]
    ]
    .sort_values(
        "abs_log_change",
        ascending=False
    )
    .head(100)
)

99.5% temporal anomaly threshold: 1.950785662694603
Flagged metric rows: 391
Affected source files: 296
Affected tickers: 193

,ticker,year,quarter,metric,normalized_value,log_change_from_previous,abs_log_change,source_file
53341,MTPS,2022,Q1,gross_profit,0.000000e+00,-11.328295,11.328295,MTPS_2022_Q1_FS.xlsx
53378,MTPS,2022,Q1,revenue,0.000000e+00,-10.739593,10.739593,MTPS_2022_Q1_FS.xlsx
26458,ETWA,2023,Q1,revenue,0.000000e+00,-10.684009,10.684009,ETWA_2023_Q1_FS.xlsx
44398,LAPD,2023,Q3,revenue,4.813373e+10,10.682449,10.682449,LAPD_2023_Q3_FS.xlsx
75319,TGRA,2022,Q1,revenue,0.000000e+00,-10.587601,10.587601,TGRA_2022_Q1_FS.xlsx
...,...,...,...,...,...,...,...,...
21206,DEWA,2023,Q1,revenue,1.761394e+12,3.636449,3.636449,DEWA_2023_Q1_FS.xlsx
7214,ATLA,2024,Q4,operating_cash_flow,-5.452371e+10,3.602214,3.602214,ATLA_2024_Q4_FS.xlsx
48137,MBSS,2024,Q1,operating_cash_flow,6.558728e+10,3.596629,3.596629,MBSS_2024_Q1_FS.xlsx
53726,MYOH,2024,Q3,operating_cash_flow,3.043933e+07,-3.584068,3.584068,MYOH_2024_Q3_FS.xlsx
4985,ARGO,2022,Q1,revenue,1.562260e+10,3.506342,3.506342,ARGO_2022_Q1_FS.xlsx

In [18]:
# CELL 17 - CHECK KNOWN CASES AND GLOBAL ANOMALY DISTRIBUTION

known_suspicious_tickers = [
    "ANTM",
    "LAPD",
    "HDTX"
]


print("KNOWN CASES")

display(
    global_metric_audit_df[
        (
            global_metric_audit_df[
                "ticker"
            ].isin(
                known_suspicious_tickers
            )
        )
        &
        (
            global_metric_audit_df[
                "temporal_anomaly"
            ]
        )
    ][
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "normalized_value",
            "abs_log_change",
            "temporal_anomaly",
            "source_file"
        ]
    ]
    .sort_values(
        [
            "ticker",
            "year",
            "quarter",
            "metric"
        ]
    )
)


print("\nMOST AFFECTED TICKERS")

print(
    global_metric_audit_df.loc[
        global_metric_audit_df[
            "temporal_anomaly"
        ],
        "ticker"
    ]
    .value_counts()
    .head(50)
)


print("\nANOMALIES BY METRIC")

print(
    global_metric_audit_df.loc[
        global_metric_audit_df[
            "temporal_anomaly"
        ],
        "metric"
    ]
    .value_counts()
)

KNOWN CASES

,ticker,year,quarter,metric,normalized_value,abs_log_change,temporal_anomaly,source_file
4190,ANTM,2023,Q2,total_assets,3.636867e+07,5.982517,True,ANTM_2023_Q2_FS.xlsx
4191,ANTM,2023,Q3,total_assets,3.550017e+13,5.989503,True,ANTM_2023_Q3_FS.xlsx
31654,HDTX,2023,Q1,revenue,5.402000e+06,3.046012,True,HDTX_2023_Q1_FS.xlsx
31641,HDTX,2025,Q1,operating_cash_flow,2.321100e+07,2.186546,True,HDTX_2025_Q1_FS.xlsx
31661,HDTX,2025,Q1,revenue,0.000000e+00,5.730783,True,HDTX_2025_Q1_FS.xlsx
44388,LAPD,2020,Q2,revenue,2.873165e+09,9.458361,True,LAPD_2020_Q2_FS.xlsx
44391,LAPD,2021,Q1,revenue,8.858115e+06,3.204115,True,LAPD_2021_Q1_FS.xlsx
44393,LAPD,2021,Q3,revenue,0.000000e+00,6.947341,True,LAPD_2021_Q3_FS.xlsx
44411,LAPD,2021,Q4,total_assets,7.793900e+07,3.092273,True,LAPD_2021_Q4_FS.xlsx
44357,LAPD,2022,Q1,gross_profit,0.000000e+00,10.425343,True,LAPD_2022_Q1_FS.xlsx
44342,LAPD,2023,Q2,cash,2.843633e+10,2.822578,True,LAPD_2023_Q2_FS.xlsx
44417,LAPD,2023,Q2,total_assets,1.944100e+11,3.345231,True,LAPD_2023_Q2_FS.xlsx
44361,LAPD,2023,Q3,gross_profit,3.222286e+09,9.508164,True,LAPD_2023_Q3_FS.xlsx
44398,LAPD,2023,Q3,revenue,4.813373e+10,10.682449,True,LAPD_2023_Q3_FS.xlsx

MOST AFFECTED TICKERS
ticker
SGER    12
LAPD     9
ALMI     8
ARGO     8
MYOH     8
MTPS     7
AIMS     6
CUAN     6
DEWA     6
IMJS     6
KOBX     6
MBSS     6
RONY     6
SMCB     6
SMMT     6
ZBRA     6
COCO     5
HDIT     5
BTON     4
FIMP     4
GTBO     4
MAPA     4
MGNA     4
PSDN     4
TRGU     4
AKKU     3
BACA     3
BAPI     3
BIKE     3
CSMI     3
HDTX     3
KOKA     3
LABA     3
NASI     3
NPGF     3
TIRT     3
AGRS     2
AISA     2
AMAG     2
AMAR     2
ANTM     2
APLN     2
ATAP     2
BBSS     2
BDMN     2
BEEF     2
BESS     2
BMAS     2
BOLT     2
DMND     2
Name: count, dtype: int64

ANOMALIES BY METRIC
metric
operating_cash_flow    193
gross_profit            64
revenue                 48
cash                    47
total_assets            20
total_liabilities       19
Name: count, dtype: int64

In [19]:
# CELL 15 - BUILD GLOBAL METRIC QUALITY FLAGS
# We do NOT alter source values.
# We only flag suspicious observations for benchmark usage.

benchmark_quality_df = (
    idx_normalized_df[
        [
            "ticker",
            "year",
            "quarter",
            "metric",
            "normalized_value",
            "source_file"
        ]
    ]
    .copy()
)


quarter_order = {
    "Q1": 1,
    "Q2": 2,
    "Q3": 3,
    "Q4": 4
}


benchmark_quality_df[
    "quarter_order"
] = (
    benchmark_quality_df[
        "quarter"
    ].map(
        quarter_order
    )
)


benchmark_quality_df = (
    benchmark_quality_df
    .sort_values(
        [
            "ticker",
            "metric",
            "year",
            "quarter_order"
        ]
    )
    .reset_index(drop=True)
)


# Previous and next normalized values
grouped = (
    benchmark_quality_df
    .groupby(
        [
            "ticker",
            "metric"
        ]
    )
)


benchmark_quality_df[
    "prev_value"
] = (
    grouped[
        "normalized_value"
    ].shift(1)
)


benchmark_quality_df[
    "next_value"
] = (
    grouped[
        "normalized_value"
    ].shift(-1)
)


def log_distance(a, b):

    if (
        pd.isna(a)
        or pd.isna(b)
    ):
        return np.nan

    a = abs(float(a))
    b = abs(float(b))

    if a == 0 or b == 0:
        return np.nan

    return abs(
        np.log10(
            a / b
        )
    )


def detect_temporal_anomaly(row):

    current = row[
        "normalized_value"
    ]

    if pd.isna(current):
        return False


    distances = []

    if pd.notna(row["prev_value"]):

        d = log_distance(
            current,
            row["prev_value"]
        )

        if pd.notna(d):
            distances.append(d)


    if pd.notna(row["next_value"]):

        d = log_distance(
            current,
            row["next_value"]
        )

        if pd.notna(d):
            distances.append(d)


    # No temporal evidence
    if not distances:
        return False


    # 2 log10 = factor 100 difference.
    # We only FLAG it, not correct it.
    return min(distances) >= 2


benchmark_quality_df[
    "temporal_anomaly"
] = (
    benchmark_quality_df.apply(
        detect_temporal_anomaly,
        axis=1
    )
)


print(
    "Total metric rows:",
    len(benchmark_quality_df)
)

print(
    "Temporal anomaly rows:",
    benchmark_quality_df[
        "temporal_anomaly"
    ].sum()
)

print(
    "Affected tickers:",
    benchmark_quality_df.loc[
        benchmark_quality_df[
            "temporal_anomaly"
        ],
        "ticker"
    ].nunique()
)


print("\nANOMALIES BY METRIC")

print(
    benchmark_quality_df.loc[
        benchmark_quality_df[
            "temporal_anomaly"
        ],
        "metric"
    ].value_counts()
)

Total metric rows: 83442
Temporal anomaly rows: 115
Affected tickers: 80

ANOMALIES BY METRIC
metric
operating_cash_flow    65
cash                   19
gross_profit           13
revenue                 6
total_assets            6
total_liabilities       6
Name: count, dtype: int64

In [22]:
# CELL 16 - APPLY QUALITY FLAGS TO FINANCIAL RATIOS
# FIXED VERSION:
# A ratio is valid only if:
# 1. the ratio value exists, and
# 2. none of its required metrics are flagged as temporal anomalies.

metric_quality_wide_df = (
    benchmark_quality_df
    .pivot_table(
        index=[
            "ticker",
            "year",
            "quarter"
        ],
        columns="metric",
        values="temporal_anomaly",
        aggfunc="max"
    )
    .reset_index()
)

metric_quality_wide_df.columns.name = None


metric_quality_wide_df = (
    metric_quality_wide_df
    .rename(
        columns={
            "gross_profit":
                "gross_profit_anomaly",

            "revenue":
                "revenue_anomaly",

            "total_liabilities":
                "total_liabilities_anomaly",

            "total_assets":
                "total_assets_anomaly",

            "cash":
                "cash_anomaly",

            "operating_cash_flow":
                "operating_cash_flow_anomaly"
        }
    )
)


benchmark_final_df = (
    benchmark_ratio_df
    .merge(
        metric_quality_wide_df,
        on=[
            "ticker",
            "year",
            "quarter"
        ],
        how="left",
        validate="one_to_one"
    )
)


anomaly_columns = [
    "gross_profit_anomaly",
    "revenue_anomaly",
    "total_liabilities_anomaly",
    "total_assets_anomaly",
    "cash_anomaly",
    "operating_cash_flow_anomaly"
]


for column in anomaly_columns:

    if column not in benchmark_final_df.columns:
        benchmark_final_df[column] = False

    benchmark_final_df[column] = (
        benchmark_final_df[
            column
        ]
        .fillna(False)
        .astype(bool)
    )


# --------------------------------------------------
# RATIO-SPECIFIC QUALITY FLAGS
# --------------------------------------------------

benchmark_final_df[
    "gross_margin_valid"
] = (
    benchmark_final_df[
        "gross_margin"
    ].notna()
    &
    ~(
        benchmark_final_df[
            "gross_profit_anomaly"
        ]
        |
        benchmark_final_df[
            "revenue_anomaly"
        ]
    )
)


benchmark_final_df[
    "debt_to_assets_valid"
] = (
    benchmark_final_df[
        "debt_to_assets"
    ].notna()
    &
    ~(
        benchmark_final_df[
            "total_liabilities_anomaly"
        ]
        |
        benchmark_final_df[
            "total_assets_anomaly"
        ]
    )
)


benchmark_final_df[
    "cash_to_assets_valid"
] = (
    benchmark_final_df[
        "cash_to_assets"
    ].notna()
    &
    ~(
        benchmark_final_df[
            "cash_anomaly"
        ]
        |
        benchmark_final_df[
            "total_assets_anomaly"
        ]
    )
)


benchmark_final_df[
    "ocf_to_revenue_valid"
] = (
    benchmark_final_df[
        "ocf_to_revenue"
    ].notna()
    &
    ~(
        benchmark_final_df[
            "operating_cash_flow_anomaly"
        ]
        |
        benchmark_final_df[
            "revenue_anomaly"
        ]
    )
)


print("VALID RATIO COUNTS")

for ratio in [
    "gross_margin",
    "debt_to_assets",
    "cash_to_assets",
    "ocf_to_revenue"
]:

    valid_col = f"{ratio}_valid"

    available_count = (
        benchmark_final_df[
            ratio
        ]
        .notna()
        .sum()
    )

    valid_count = (
        benchmark_final_df[
            valid_col
        ]
        .sum()
    )

    excluded_count = (
        available_count
        - valid_count
    )

    print(
        f"{ratio}: "
        f"{valid_count} valid / "
        f"{available_count} available / "
        f"{excluded_count} excluded"
    )

VALID RATIO COUNTS
gross_margin: 12332 valid / 12349 available / 17 excluded
debt_to_assets: 14746 valid / 14753 available / 7 excluded
cash_to_assets: 13758 valid / 13778 available / 20 excluded
ocf_to_revenue: 12910 valid / 12963 available / 53 excluded

In [23]:
# CELL 17 - BUILD QUALITY-CONTROLLED RATIO DATASET

quality_ratio_df = (
    benchmark_final_df[
        [
            "ticker",
            "year",
            "quarter",
            "gross_margin",
            "gross_margin_valid",
            "debt_to_assets",
            "debt_to_assets_valid",
            "cash_to_assets",
            "cash_to_assets_valid",
            "ocf_to_revenue",
            "ocf_to_revenue_valid"
        ]
    ]
    .copy()
)


# Create benchmark-safe versions.
# Invalid observations remain in the dataframe for provenance,
# but are excluded from benchmark statistics by becoming NaN.

for ratio in [
    "gross_margin",
    "debt_to_assets",
    "cash_to_assets",
    "ocf_to_revenue"
]:

    valid_column = f"{ratio}_valid"
    benchmark_column = f"{ratio}_benchmark"

    quality_ratio_df[
        benchmark_column
    ] = np.where(
        quality_ratio_df[
            valid_column
        ],
        quality_ratio_df[
            ratio
        ],
        np.nan
    )


benchmark_ratio_columns = [
    "gross_margin_benchmark",
    "debt_to_assets_benchmark",
    "cash_to_assets_benchmark",
    "ocf_to_revenue_benchmark"
]


print("BENCHMARK-SAFE RATIO AVAILABILITY")

for column in benchmark_ratio_columns:

    print(
        column,
        ":",
        quality_ratio_df[
            column
        ].notna().sum()
    )


print("\nBENCHMARK-SAFE DISTRIBUTION")

for column in benchmark_ratio_columns:

    print("\n", column)

    print(
        quality_ratio_df[
            column
        ].describe(
            percentiles=[
                0.05,
                0.25,
                0.50,
                0.75,
                0.95
            ]
        )
    )

BENCHMARK-SAFE RATIO AVAILABILITY
gross_margin_benchmark : 12332
debt_to_assets_benchmark : 14746
cash_to_assets_benchmark : 13758
ocf_to_revenue_benchmark : 12910

BENCHMARK-SAFE DISTRIBUTION

 gross_margin_benchmark
count    12332.000000
mean        -8.940889
std        608.058487
min     -57082.968401
5%          -0.008175
25%          0.125768
50%          0.251172
75%          0.437408
95%          0.701815
max          1.142575
Name: gross_margin_benchmark, dtype: float64

 debt_to_assets_benchmark
count    14746.000000
mean         2.690056
std         72.399953
min          0.000008
5%           0.069907
25%          0.255347
50%          0.450176
75%          0.660683
95%          1.019874
max       3792.755752
Name: debt_to_assets_benchmark, dtype: float64

 cash_to_assets_benchmark
count    1.375800e+04
mean     9.706857e-02
std      1.229513e-01
min      1.151412e-07
5%       1.781631e-03
25%      1.509420e-02
50%      5.236307e-02
75%      1.336019e-01
95%      3.270472e-01
max      9.682161e-01
Name: cash_to_assets_benchmark, dtype: float64

 ocf_to_revenue_benchmark
count    12910.000000
mean        -1.500199
std         91.152830
min      -7794.180297
5%          -0.891228
25%         -0.044744
50%          0.061471
75%          0.199658
95%          0.558679
max        704.607807
Name: ocf_to_revenue_benchmark, dtype: float64

In [24]:
# CELL 18 - CALCULATE OVERALL IDX BENCHMARK STATISTICS

overall_benchmark_rows = []


ratio_mapping = {
    "gross_margin":
        "gross_margin_benchmark",

    "debt_to_assets":
        "debt_to_assets_benchmark",

    "cash_to_assets":
        "cash_to_assets_benchmark",

    "ocf_to_revenue":
        "ocf_to_revenue_benchmark",
}


for ratio_name, column_name in ratio_mapping.items():

    values = (
        quality_ratio_df[
            column_name
        ]
        .dropna()
    )


    overall_benchmark_rows.append(
        {
            "benchmark_scope":
                "IDX_ALL",

            "ratio":
                ratio_name,

            "count":
                len(values),

            "p05":
                values.quantile(0.05),

            "p25":
                values.quantile(0.25),

            "median":
                values.quantile(0.50),

            "p75":
                values.quantile(0.75),

            "p95":
                values.quantile(0.95),

            "mean":
                values.mean(),

            "std":
                values.std(),
        }
    )


overall_benchmark_df = pd.DataFrame(
    overall_benchmark_rows
)


display(
    overall_benchmark_df
)

,benchmark_scope,ratio,count,p05,p25,median,p75,p95,mean,std
0,IDX_ALL,gross_margin,12332,-0.008175,0.125768,0.251172,0.437408,0.701815,-8.940889,608.058487
1,IDX_ALL,debt_to_assets,14746,0.069907,0.255347,0.450176,0.660683,1.019874,2.690056,72.399953
2,IDX_ALL,cash_to_assets,13758,0.001782,0.015094,0.052363,0.133602,0.327047,0.097069,0.122951
3,IDX_ALL,ocf_to_revenue,12910,-0.891228,-0.044744,0.061471,0.199658,0.558679,-1.500199,91.152830

In [25]:
# CELL 19 - CALCULATE IDX BENCHMARK BY YEAR AND QUARTER

period_benchmark_rows = []


for (
    year,
    quarter
), group in quality_ratio_df.groupby(
    [
        "year",
        "quarter"
    ]
):

    for ratio_name, column_name in ratio_mapping.items():

        values = (
            group[
                column_name
            ]
            .dropna()
        )


        if len(values) == 0:
            continue


        period_benchmark_rows.append(
            {
                "benchmark_scope":
                    "IDX_PERIOD",

                "year":
                    year,

                "quarter":
                    quarter,

                "ratio":
                    ratio_name,

                "count":
                    len(values),

                "p05":
                    values.quantile(0.05),

                "p25":
                    values.quantile(0.25),

                "median":
                    values.quantile(0.50),

                "p75":
                    values.quantile(0.75),

                "p95":
                    values.quantile(0.95),

                "mean":
                    values.mean(),

                "std":
                    values.std(),
            }
        )


period_benchmark_df = pd.DataFrame(
    period_benchmark_rows
)


print(
    "Period benchmark rows:",
    len(period_benchmark_df)
)


display(
    period_benchmark_df
    .sort_values(
        [
            "year",
            "quarter",
            "ratio"
        ]
    )
    .head(50)
)

Period benchmark rows: 84

,benchmark_scope,year,quarter,ratio,count,p05,p25,median,p75,p95,mean,std
2,IDX_PERIOD,2020,Q1,cash_to_assets,590,0.001767,0.014940,0.049326,0.116306,0.292905,0.089435,0.118615
1,IDX_PERIOD,2020,Q1,debt_to_assets,633,0.075756,0.288474,0.493859,0.697972,0.986329,2.185317,38.429911
0,IDX_PERIOD,2020,Q1,gross_margin,521,-0.088255,0.117811,0.231797,0.429462,0.720901,0.224286,0.740803
3,IDX_PERIOD,2020,Q1,ocf_to_revenue,546,-1.069715,-0.066307,0.065453,0.232602,0.718511,-0.101741,4.112210
6,IDX_PERIOD,2020,Q2,cash_to_assets,603,0.001535,0.012750,0.043359,0.114903,0.297498,0.087169,0.119216
5,IDX_PERIOD,2020,Q2,debt_to_assets,648,0.079406,0.271885,0.484249,0.678927,0.973803,2.147498,37.284593
4,IDX_PERIOD,2020,Q2,gross_margin,535,-0.139149,0.110616,0.220658,0.401127,0.705571,0.180686,1.232400
7,IDX_PERIOD,2020,Q2,ocf_to_revenue,564,-1.005428,-0.070397,0.059895,0.205744,0.599636,-0.331865,3.965024
10,IDX_PERIOD,2020,Q3,cash_to_assets,609,0.001643,0.012859,0.044257,0.113060,0.293245,0.086861,0.119986
9,IDX_PERIOD,2020,Q3,debt_to_assets,654,0.080322,0.280957,0.486065,0.687861,0.988160,3.963350,83.264821
8,IDX_PERIOD,2020,Q3,gross_margin,541,-0.125025,0.103108,0.211833,0.396850,0.705250,0.181067,1.132405
11,IDX_PERIOD,2020,Q3,ocf_to_revenue,570,-1.016622,-0.042323,0.063285,0.202321,0.536361,-0.768746,12.062692
14,IDX_PERIOD,2020,Q4,cash_to_assets,616,0.002105,0.015588,0.048020,0.131101,0.313356,0.095395,0.125188
13,IDX_PERIOD,2020,Q4,debt_to_assets,664,0.076630,0.276831,0.481759,0.692225,0.979422,5.922709,134.363683
12,IDX_PERIOD,2020,Q4,gross_margin,548,-0.110721,0.109131,0.223702,0.416782,0.699975,0.139454,2.473270
15,IDX_PERIOD,2020,Q4,ocf_to_revenue,577,-0.790776,-0.011058,0.089939,0.205315,0.497931,-0.466551,6.446890
18,IDX_PERIOD,2021,Q1,cash_to_assets,595,0.001287,0.013581,0.047704,0.128537,0.331415,0.095665,0.128308
17,IDX_PERIOD,2021,Q1,debt_to_assets,642,0.073906,0.274521,0.477444,0.687096,1.013678,5.331094,117.209165
16,IDX_PERIOD,2021,Q1,gross_margin,533,-0.346621,0.118897,0.236178,0.435331,0.704475,-1.563071,39.109701
19,IDX_PERIOD,2021,Q1,ocf_to_revenue,556,-1.301010,-0.057185,0.077781,0.241642,0.693754,-1.354307,21.895417
22,IDX_PERIOD,2021,Q2,cash_to_assets,613,0.001311,0.012339,0.048312,0.129751,0.322899,0.096631,0.129640
21,IDX_PERIOD,2021,Q2,debt_to_assets,662,0.071317,0.269918,0.477259,0.694310,1.018274,3.295133,65.016419
20,IDX_PERIOD,2021,Q2,gross_margin,552,-0.253994,0.124414,0.249671,0.434480,0.698607,-3.134467,76.491532
23,IDX_PERIOD,2021,Q2,ocf_to_revenue,576,-1.040736,-0.052249,0.063507,0.215140,0.545816,-2.210989,33.863045
26,IDX_PERIOD,2021,Q3,cash_to_assets,594,0.001682,0.014709,0.047596,0.128160,0.308165,0.097735,0.134636
25,IDX_PERIOD,2021,Q3,debt_to_assets,641,0.075541,0.278872,0.477319,0.695620,1.038712,1.723842,22.429923
24,IDX_PERIOD,2021,Q3,gross_margin,534,-0.220914,0.120758,0.245178,0.432470,0.687139,0.115252,1.975557
27,IDX_PERIOD,2021,Q3,ocf_to_revenue,558,-0.935245,-0.040105,0.067816,0.201448,0.522802,-0.197698,2.837370
30,IDX_PERIOD,2021,Q4,cash_to_assets,634,0.002513,0.018269,0.059040,0.152693,0.372314,0.109135,0.135826
29,IDX_PERIOD,2021,Q4,debt_to_assets,684,0.080961,0.278268,0.466429,0.663239,1.017211,5.785697,122.523670
28,IDX_PERIOD,2021,Q4,gross_margin,576,0.002948,0.133542,0.247012,0.437679,0.710034,0.215421,0.763053
31,IDX_PERIOD,2021,Q4,ocf_to_revenue,602,-0.599334,-0.010893,0.079898,0.228232,0.526445,-0.068783,3.084712
34,IDX_PERIOD,2022,Q1,cash_to_assets,635,0.002079,0.016752,0.054096,0.136432,0.342866,0.102342,0.131655
33,IDX_PERIOD,2022,Q1,debt_to_assets,684,0.074881,0.269864,0.464021,0.669370,1.041627,5.233536,110.763006
32,IDX_PERIOD,2022,Q1,gross_margin,566,0.008820,0.134386,0.261250,0.448271,0.764495,0.251680,0.653448
35,IDX_PERIOD,2022,Q1,ocf_to_revenue,594,-1.075852,-0.106620,0.060536,0.214867,0.565639,-0.071424,4.554848
38,IDX_PERIOD,2022,Q2,cash_to_assets,672,0.001585,0.016868,0.053445,0.138411,0.357041,0.103370,0.130192
37,IDX_PERIOD,2022,Q2,debt_to_assets,720,0.070079,0.266858,0.456012,0.668089,1.050695,6.069702,137.077634
36,IDX_PERIOD,2022,Q2,gross_margin,605,0.013580,0.136998,0.265718,0.459569,0.736649,0.256655,0.775661
39,IDX_PERIOD,2022,Q2,ocf_to_revenue,633,-1.116610,-0.064323,0.033784,0.176155,0.571857,-0.240475,3.958431
42,IDX_PERIOD,2022,Q3,cash_to_assets,657,0.001688,0.015890,0.053293,0.135132,0.347884,0.098559,0.125619
41,IDX_PERIOD,2022,Q3,debt_to_assets,706,0.078768,0.265698,0.455073,0.664573,1.051544,6.299450,142.821148
40,IDX_PERIOD,2022,Q3,gross_margin,587,0.022317,0.134487,0.258009,0.463121,0.712013,0.220450,1.209733
43,IDX_PERIOD,2022,Q3,ocf_to_revenue,616,-0.768527,-0.052904,0.045709,0.192512,0.538602,-0.042547,1.152391
46,IDX_PERIOD,2022,Q4,cash_to_assets,707,0.001627,0.015489,0.063649,0.144065,0.358982,0.104706,0.124534
45,IDX_PERIOD,2022,Q4,debt_to_assets,759,0.072007,0.242427,0.450129,0.654689,1.055786,1.367613,11.802948
44,IDX_PERIOD,2022,Q4,gross_margin,637,0.011811,0.128610,0.258631,0.462529,0.723960,0.179085,1.906941
47,IDX_PERIOD,2022,Q4,ocf_to_revenue,672,-0.502694,-0.017536,0.057968,0.200041,0.490945,0.002683,1.096962
50,IDX_PERIOD,2023,Q1,cash_to_assets,674,0.001955,0.015362,0.054703,0.134899,0.343488,0.099573,0.122302
49,IDX_PERIOD,2023,Q1,debt_to_assets,718,0.074415,0.247766,0.437257,0.648435,1.109071,1.348507,10.640639

In [26]:
# CELL 20 - BUILD FINAL IDX BENCHMARK TABLES

final_overall_benchmark_df = (
    overall_benchmark_df[
        [
            "benchmark_scope",
            "ratio",
            "count",
            "p05",
            "p25",
            "median",
            "p75",
            "p95"
        ]
    ]
    .copy()
)


final_period_benchmark_df = (
    period_benchmark_df[
        [
            "benchmark_scope",
            "year",
            "quarter",
            "ratio",
            "count",
            "p05",
            "p25",
            "median",
            "p75",
            "p95"
        ]
    ]
    .copy()
)


print("FINAL OVERALL BENCHMARK")

display(
    final_overall_benchmark_df
)


print("\nFINAL PERIOD BENCHMARK ROWS")

print(
    len(final_period_benchmark_df)
)


display(
    final_period_benchmark_df
    .sort_values(
        [
            "year",
            "quarter",
            "ratio"
        ]
    )
    .head(40)
)

FINAL OVERALL BENCHMARK

,benchmark_scope,ratio,count,p05,p25,median,p75,p95
0,IDX_ALL,gross_margin,12332,-0.008175,0.125768,0.251172,0.437408,0.701815
1,IDX_ALL,debt_to_assets,14746,0.069907,0.255347,0.450176,0.660683,1.019874
2,IDX_ALL,cash_to_assets,13758,0.001782,0.015094,0.052363,0.133602,0.327047
3,IDX_ALL,ocf_to_revenue,12910,-0.891228,-0.044744,0.061471,0.199658,0.558679

FINAL PERIOD BENCHMARK ROWS
84

,benchmark_scope,year,quarter,ratio,count,p05,p25,median,p75,p95
2,IDX_PERIOD,2020,Q1,cash_to_assets,590,0.001767,0.014940,0.049326,0.116306,0.292905
1,IDX_PERIOD,2020,Q1,debt_to_assets,633,0.075756,0.288474,0.493859,0.697972,0.986329
0,IDX_PERIOD,2020,Q1,gross_margin,521,-0.088255,0.117811,0.231797,0.429462,0.720901
3,IDX_PERIOD,2020,Q1,ocf_to_revenue,546,-1.069715,-0.066307,0.065453,0.232602,0.718511
6,IDX_PERIOD,2020,Q2,cash_to_assets,603,0.001535,0.012750,0.043359,0.114903,0.297498
5,IDX_PERIOD,2020,Q2,debt_to_assets,648,0.079406,0.271885,0.484249,0.678927,0.973803
4,IDX_PERIOD,2020,Q2,gross_margin,535,-0.139149,0.110616,0.220658,0.401127,0.705571
7,IDX_PERIOD,2020,Q2,ocf_to_revenue,564,-1.005428,-0.070397,0.059895,0.205744,0.599636
10,IDX_PERIOD,2020,Q3,cash_to_assets,609,0.001643,0.012859,0.044257,0.113060,0.293245
9,IDX_PERIOD,2020,Q3,debt_to_assets,654,0.080322,0.280957,0.486065,0.687861,0.988160
8,IDX_PERIOD,2020,Q3,gross_margin,541,-0.125025,0.103108,0.211833,0.396850,0.705250
11,IDX_PERIOD,2020,Q3,ocf_to_revenue,570,-1.016622,-0.042323,0.063285,0.202321,0.536361
14,IDX_PERIOD,2020,Q4,cash_to_assets,616,0.002105,0.015588,0.048020,0.131101,0.313356
13,IDX_PERIOD,2020,Q4,debt_to_assets,664,0.076630,0.276831,0.481759,0.692225,0.979422
12,IDX_PERIOD,2020,Q4,gross_margin,548,-0.110721,0.109131,0.223702,0.416782,0.699975
15,IDX_PERIOD,2020,Q4,ocf_to_revenue,577,-0.790776,-0.011058,0.089939,0.205315,0.497931
18,IDX_PERIOD,2021,Q1,cash_to_assets,595,0.001287,0.013581,0.047704,0.128537,0.331415
17,IDX_PERIOD,2021,Q1,debt_to_assets,642,0.073906,0.274521,0.477444,0.687096,1.013678
16,IDX_PERIOD,2021,Q1,gross_margin,533,-0.346621,0.118897,0.236178,0.435331,0.704475
19,IDX_PERIOD,2021,Q1,ocf_to_revenue,556,-1.301010,-0.057185,0.077781,0.241642,0.693754
22,IDX_PERIOD,2021,Q2,cash_to_assets,613,0.001311,0.012339,0.048312,0.129751,0.322899
21,IDX_PERIOD,2021,Q2,debt_to_assets,662,0.071317,0.269918,0.477259,0.694310,1.018274
20,IDX_PERIOD,2021,Q2,gross_margin,552,-0.253994,0.124414,0.249671,0.434480,0.698607
23,IDX_PERIOD,2021,Q2,ocf_to_revenue,576,-1.040736,-0.052249,0.063507,0.215140,0.545816
26,IDX_PERIOD,2021,Q3,cash_to_assets,594,0.001682,0.014709,0.047596,0.128160,0.308165
25,IDX_PERIOD,2021,Q3,debt_to_assets,641,0.075541,0.278872,0.477319,0.695620,1.038712
24,IDX_PERIOD,2021,Q3,gross_margin,534,-0.220914,0.120758,0.245178,0.432470,0.687139
27,IDX_PERIOD,2021,Q3,ocf_to_revenue,558,-0.935245,-0.040105,0.067816,0.201448,0.522802
30,IDX_PERIOD,2021,Q4,cash_to_assets,634,0.002513,0.018269,0.059040,0.152693,0.372314
29,IDX_PERIOD,2021,Q4,debt_to_assets,684,0.080961,0.278268,0.466429,0.663239,1.017211
28,IDX_PERIOD,2021,Q4,gross_margin,576,0.002948,0.133542,0.247012,0.437679,0.710034
31,IDX_PERIOD,2021,Q4,ocf_to_revenue,602,-0.599334,-0.010893,0.079898,0.228232,0.526445
34,IDX_PERIOD,2022,Q1,cash_to_assets,635,0.002079,0.016752,0.054096,0.136432,0.342866
33,IDX_PERIOD,2022,Q1,debt_to_assets,684,0.074881,0.269864,0.464021,0.669370,1.041627
32,IDX_PERIOD,2022,Q1,gross_margin,566,0.008820,0.134386,0.261250,0.448271,0.764495
35,IDX_PERIOD,2022,Q1,ocf_to_revenue,594,-1.075852,-0.106620,0.060536,0.214867,0.565639
38,IDX_PERIOD,2022,Q2,cash_to_assets,672,0.001585,0.016868,0.053445,0.138411,0.357041
37,IDX_PERIOD,2022,Q2,debt_to_assets,720,0.070079,0.266858,0.456012,0.668089,1.050695
36,IDX_PERIOD,2022,Q2,gross_margin,605,0.013580,0.136998,0.265718,0.459569,0.736649
39,IDX_PERIOD,2022,Q2,ocf_to_revenue,633,-1.116610,-0.064323,0.033784,0.176155,0.571857

In [27]:
# CELL 21 - SAVE FINAL IDX BENCHMARK DATASETS

FINAL_RATIO_FILE = Path(
    "data/idx_financial/benchmark/idx_financial_ratio_benchmark_ready.csv"
)

FINAL_OVERALL_BENCHMARK_FILE = Path(
    "data/idx_financial/benchmark/idx_financial_benchmark_overall.csv"
)

FINAL_PERIOD_BENCHMARK_FILE = Path(
    "data/idx_financial/benchmark/idx_financial_benchmark_by_period.csv"
)


quality_ratio_df.to_csv(
    FINAL_RATIO_FILE,
    index=False
)


final_overall_benchmark_df.to_csv(
    FINAL_OVERALL_BENCHMARK_FILE,
    index=False
)


final_period_benchmark_df.to_csv(
    FINAL_PERIOD_BENCHMARK_FILE,
    index=False
)


print(
    "Saved ratio-level benchmark-ready data:",
    FINAL_RATIO_FILE
)

print(
    "Saved overall benchmark:",
    FINAL_OVERALL_BENCHMARK_FILE
)

print(
    "Saved period benchmark:",
    FINAL_PERIOD_BENCHMARK_FILE
)


print("\nROWS")

print(
    "Ratio-level rows:",
    len(quality_ratio_df)
)

print(
    "Overall benchmark rows:",
    len(final_overall_benchmark_df)
)

print(
    "Period benchmark rows:",
    len(final_period_benchmark_df)
)

Saved ratio-level benchmark-ready data: data\idx_financial_ratio_benchmark_ready.csv
Saved overall benchmark: data\idx_financial_benchmark_overall.csv
Saved period benchmark: data\idx_financial_benchmark_by_period.csv

ROWS
Ratio-level rows: 14753
Overall benchmark rows: 4
Period benchmark rows: 84