In [1]:
# Keep repository-relative paths valid from notebook subfolders.
from pathlib import Path
import os

os.chdir(next(
    root for root in (Path.cwd(), *Path.cwd().parents)
    if (root / "notebooks").is_dir() and (root / "requirements.txt").is_file()
))

# Resolve legacy IDX paths stored in existing CSVs without rewriting the data.
def _relocated_idx_path(value):
    text = str(value).replace("\\", "/")
    old_repo = "AI-Builders-Hackhaton-2026-Backend/"
    if old_repo in text:
        text = text.split(old_repo, 1)[1]
    old_raw = "data/idx_financial_statements/"
    if text.startswith(old_raw):
        text = "data/idx_financial/raw/" + text[len(old_raw):]
    return Path(text)

from pathlib import Path
import pandas as pd
import re
from collections import Counter, defaultdict

from openpyxl import load_workbook
from tqdm.auto import tqdm

e:\BINUS_CODING\Ai Builders Hackhaton\AI-Builders-Hackhaton-2026-Backend\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
SCAN_FILE = Path(
    "data/idx_financial/inventory/idx_financial_file_scan.csv"
)

OUTPUT_FILE = Path(
    "data/idx_financial/discovery/idx_financial_label_discovery.csv"
)

CHECKPOINT_FILE = Path(
    "data/idx_financial/discovery/idx_financial_label_discovery_checkpoint.csv"
)

print("Scan file exists:", SCAN_FILE.exists())

Scan file exists: True

In [3]:
scan_df = pd.read_csv(
    SCAN_FILE
)

valid_files_df = (
    scan_df[
        scan_df["scan_status"] == "VALID"
    ]
    .copy()
)

print("Valid XLSX files:", len(valid_files_df))
print("Unique tickers:", valid_files_df["ticker"].nunique())

Valid XLSX files: 15821
Unique tickers: 948

In [4]:
def resolve_file_path(path_text):

    path = _relocated_idx_path(
        str(path_text)
    )

    if path.exists():
        return path

    alternative = Path.cwd() / path

    if alternative.exists():
        return alternative

    return None

In [5]:
def normalize_label(value):

    if value is None:
        return ""

    text = str(value).strip().lower()

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text

In [10]:
SKIP_SHEETS = {
    "context",
    "inlinexbrl",
    "hidden",
    "token",
    "1000000"
}

def should_skip_sheet(sheet_name):

    return (
        str(sheet_name)
        .strip()
        .lower()
        in SKIP_SHEETS
    )

In [11]:
def is_useful_label(value):

    if not isinstance(value, str):
        return False

    text = normalize_label(value)

    if not text:
        return False

    if len(text) < 3:
        return False

    if text.isdigit():
        return False

    return True

In [12]:
def extract_labels_from_file(row):

    file_path = resolve_file_path(
        row["file_path"]
    )

    results = []

    if file_path is None:
        return results

    try:

        workbook = load_workbook(
            _relocated_idx_path(file_path),
            read_only=True,
            data_only=True
        )

        for sheet_name in workbook.sheetnames:

            if should_skip_sheet(
                sheet_name
            ):
                continue

            worksheet = workbook[
                sheet_name
            ]

            for row_number, cells in enumerate(
                worksheet.iter_rows(
                    values_only=True
                ),
                start=1
            ):

                for column_index, value in enumerate(
                    cells
                ):

                    if not is_useful_label(
                        value
                    ):
                        continue

                    label_norm = normalize_label(
                        value
                    )

                    results.append({
                        "ticker": row["ticker"],
                        "year": row["year"],
                        "quarter": row["quarter"],
                        "source_file": row["file_name"],
                        "source_path": row["file_path"],
                        "source_sheet": sheet_name,
                        "row_number": row_number,
                        "column_index": column_index,
                        "source_label": value,
                        "normalized_label": label_norm
                    })

        workbook.close()

    except Exception:
        pass

    return results

In [13]:
test_df = valid_files_df.head(3)

test_results = []

for _, row in tqdm(
    test_df.iterrows(),
    total=len(test_df),
    desc="Testing label discovery",
    unit="file"
):

    test_results.extend(
        extract_labels_from_file(
            row
        )
    )

test_labels_df = pd.DataFrame(
    test_results
)

print("Labels found:", len(test_labels_df))

display(
    test_labels_df.head(100)
)

Testing label discovery: 100%|██████████| 3/3 [00:01<00:00,  1.94file/s]

Labels found: 24732

,ticker,year,quarter,source_file,source_path,source_sheet,row_number,column_index,source_label,normalized_label
0,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,1,0,[1210000] Statement of financial position pres...,[1210000] statement of financial position pres...
1,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,3,0,Laporan posisi keuangan,laporan posisi keuangan
2,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,3,2,Statement of financial position,statement of financial position
3,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,4,1,CurrentYearInstant,currentyearinstant
4,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,4,2,PriorEndYearInstant,priorendyearinstant
...,...,...,...,...,...,...,...,...,...,...
95,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,50,0,Pajak dibayar dimuka lancar,pajak dibayar dimuka lancar
96,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,50,3,Current prepaid taxes,current prepaid taxes
97,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,51,0,Klaim atas pengembalian pajak lancar,klaim atas pengembalian pajak lancar
98,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,51,3,Current claims for tax refund,current claims for tax refund
99,ZYRX,2025,Q1,ZYRX_2025_Q1_FS.xlsx,data\idx_financial_statements\Financial_Statem...,1210000,52,0,Biaya pengupasan tanah yang ditangguhkan lancar,biaya pengupasan tanah yang ditangguhkan lancar

In [14]:
sheet_summary = (
    test_labels_df
    .groupby(
        [
            "ticker",
            "source_sheet"
        ]
    )
    .size()
    .reset_index(
        name="label_count"
    )
)

display(
    sheet_summary
)

   ticker source_sheet  label_count
0    ZINC      1210000          543
1    ZINC      1311000          127
2    ZINC      1410000          129
3    ZINC    1410000PY          129
4    ZINC      1510000          357
..    ...          ...          ...
75   ZYRX      1691100            8
76   ZYRX      1692000         1237
77   ZYRX      1693000         1321
78   ZYRX      1693100            9
79   ZYRX      1696000         1237

[80 rows x 3 columns]

In [15]:
profit_test_df = (
    test_labels_df[
        test_labels_df[
            "normalized_label"
        ]
        .str.contains(
            r"profit|laba|income",
            regex=True,
            na=False
        )
    ]
    .copy()
)

print(
    "Profit-related labels found:",
    len(profit_test_df)
)

display(
    profit_test_df[
        [
            "ticker",
            "source_sheet",
            "row_number",
            "source_label",
            "normalized_label"
        ]
    ].head(200)
)

Profit-related labels found: 307

,ticker,source_sheet,row_number,source_label,normalized_label
21,ZYRX,1210000,13,Aset keuangan lancar yang diukur pada nilai wa...,aset keuangan lancar yang diukur pada nilai wa...
22,ZYRX,1210000,13,Current financial assets at fair value through...,current financial assets at fair value through...
24,ZYRX,1210000,14,Current financial assets fair value through ot...,current financial assets fair value through ot...
157,ZYRX,1210000,81,Aset keuangan tidak lancar yang diukur pada ni...,aset keuangan tidak lancar yang diukur pada ni...
158,ZYRX,1210000,81,Non-current financial assets at fair value thr...,non-current financial assets at fair value thr...
...,...,...,...,...,...
9169,ZONE,1510000,34,Income taxes refunded (paid) from operating ac...,income taxes refunded (paid) from operating ac...
9175,ZONE,1510000,37,Payments for corporate income tax,payments for corporate income tax
9264,ZONE,1510000,82,Pencairan (penempatan) aset keuangan yang diuk...,pencairan (penempatan) aset keuangan yang diuk...
9265,ZONE,1510000,82,Withdrawal (placement) of financial assets at ...,withdrawal (placement) of financial assets at ...
9267,ZONE,1510000,83,Withdrawal (placement) of financial assets fai...,withdrawal (placement) of financial assets fai...

In [16]:
cashflow_test_df = (
    test_labels_df[
        test_labels_df[
            "normalized_label"
        ]
        .str.contains(
            r"cash flow|arus kas|operating activit|aktivitas operasi",
            regex=True,
            na=False
        )
    ]
    .copy()
)

print(
    "Cash-flow-related labels found:",
    len(cashflow_test_df)
)

display(
    cashflow_test_df[
        [
            "ticker",
            "source_sheet",
            "row_number",
            "source_label",
            "normalized_label"
        ]
    ].head(200)
)

Cash-flow-related labels found: 159

,ticker,source_sheet,row_number,source_label,normalized_label
517,ZYRX,1210000,261,Cadangan lindung nilai arus kas,cadangan lindung nilai arus kas
518,ZYRX,1210000,261,Reserve of cash flow hedges,reserve of cash flow hedges
622,ZYRX,1321000,42,"Keuntungan (kerugian) lindung nilai arus kas, ...","keuntungan (kerugian) lindung nilai arus kas, ..."
623,ZYRX,1321000,42,"Gains (losses) on cash flow hedges, before tax","gains (losses) on cash flow hedges, before tax"
624,ZYRX,1321000,43,Penyesuaian reklasifikasi atas lindung nilai a...,penyesuaian reklasifikasi atas lindung nilai a...
...,...,...,...,...,...
17605,ZINC,1510000,174,Total net cash flows received from (used in) f...,total net cash flows received from (used in) f...
17608,ZINC,1510000,176,"Kas dan setara kas arus kas, awal periode","kas dan setara kas arus kas, awal periode"
17609,ZINC,1510000,176,"Cash and cash equivalents cash flows, beginnin...","cash and cash equivalents cash flows, beginnin..."
17616,ZINC,1510000,180,"Kas dan setara kas arus kas, akhir periode","kas dan setara kas arus kas, akhir periode"
17617,ZINC,1510000,180,"Cash and cash equivalents cash flows, end of t...","cash and cash equivalents cash flows, end of t..."

In [17]:
profit_label_summary = (
    profit_test_df
    .groupby(
        "normalized_label"
    )
    .agg(
        occurrences=(
            "normalized_label",
            "size"
        ),
        unique_tickers=(
            "ticker",
            "nunique"
        ),
        example_label=(
            "source_label",
            "first"
        )
    )
    .reset_index()
    .sort_values(
        [
            "unique_tickers",
            "occurrences"
        ],
        ascending=[
            False,
            False
        ]
    )
)

display(
    profit_label_summary.head(200)
)

,normalized_label,occurrences,unique_tickers,example_label
91,reserve for changes in fair value of fair valu...,9,3,Reserve for changes in fair value of fair valu...
93,saldo laba yang belum ditentukan penggunaannya,9,3,Saldo laba yang belum ditentukan penggunaannya
94,saldo laba yang telah ditentukan penggunaannya,9,3,Saldo laba yang telah ditentukan penggunaannya
34,laba (rugi),6,3,Laba (rugi)
52,laporan laba rugi dan penghasilan komprehensif...,6,3,Laporan laba rugi dan penghasilan komprehensif...
...,...,...,...,...
102,tax on other comprehensive income,1,1,Tax on other comprehensive income
106,total other comprehensive income that may be r...,1,1,Total other comprehensive income that may be r...
108,total other comprehensive income that will not...,1,1,Total other comprehensive income that will not...
110,"total other comprehensive income, before tax",1,1,"Total other comprehensive income, before tax"
116,unrealised gains (losses) on changes in fair v...,1,1,Unrealised gains (losses) on changes in fair v...

In [18]:
cashflow_label_summary = (
    cashflow_test_df
    .groupby(
        "normalized_label"
    )
    .agg(
        occurrences=(
            "normalized_label",
            "size"
        ),
        unique_tickers=(
            "ticker",
            "nunique"
        ),
        example_label=(
            "source_label",
            "first"
        )
    )
    .reset_index()
    .sort_values(
        [
            "unique_tickers",
            "occurrences"
        ],
        ascending=[
            False,
            False
        ]
    )
)

display(
    cashflow_label_summary.head(200)
)

,normalized_label,occurrences,unique_tickers,example_label
5,cadangan lindung nilai arus kas,9,3,Cadangan lindung nilai arus kas
48,reserve of cash flow hedges,9,3,Reserve of cash flow hedges
28,laporan arus kas,6,3,Laporan arus kas
49,statement of cash flows,6,3,Statement of cash flows
0,"[1510000] statement of cash flows, direct meth...",3,3,"[1510000] Statement of cash flows, direct meth..."
1,arus kas dari aktivitas investasi,3,3,Arus kas dari aktivitas investasi
2,arus kas dari aktivitas operasi,3,3,Arus kas dari aktivitas operasi
3,arus kas dari aktivitas pendanaan,3,3,Arus kas dari aktivitas pendanaan
4,arus kas sebelum perubahan dalam aset dan liab...,3,3,Arus kas sebelum perubahan dalam aset dan liab...
6,"cash and cash equivalents cash flows, beginnin...",3,3,"Cash and cash equivalents cash flows, beginnin..."
7,"cash and cash equivalents cash flows, end of t...",3,3,"Cash and cash equivalents cash flows, end of t..."
8,cash flows from financing activities,3,3,Cash flows from financing activities
9,cash flows from investing activities,3,3,Cash flows from investing activities
10,cash flows from operating activities,3,3,Cash flows from operating activities
11,cash payments from operating activities,3,3,Cash payments from operating activities
12,cash receipts from operating activities,3,3,Cash receipts from operating activities
13,dividends paid from operating activities,3,3,Dividends paid from operating activities
14,dividends received from operating activities,3,3,Dividends received from operating activities
18,income taxes refunded (paid) from operating ac...,3,3,Income taxes refunded (paid) from operating ac...
19,interests paid from operating activities,3,3,Interests paid from operating activities
20,interests received from operating activities,3,3,Interests received from operating activities
21,jumlah arus kas bersih yang diperoleh dari (di...,3,3,Jumlah arus kas bersih yang diperoleh dari (di...
22,jumlah arus kas bersih yang diperoleh dari (di...,3,3,Jumlah arus kas bersih yang diperoleh dari (di...
23,jumlah arus kas bersih yang diperoleh dari (di...,3,3,Jumlah arus kas bersih yang diperoleh dari (di...
24,"kas dan setara kas arus kas, akhir periode",3,3,"Kas dan setara kas arus kas, akhir periode"
25,"kas dan setara kas arus kas, awal periode",3,3,"Kas dan setara kas arus kas, awal periode"
30,net cash flows received from (used in) operati...,3,3,Net cash flows received from (used in) operati...
31,other cash inflows (outflows) from operating a...,3,3,Other cash inflows (outflows) from operating a...
32,other cash payments for operating activities,3,3,Other cash payments for operating activities
33,other cash receipts from operating activities,3,3,Other cash receipts from operating activities
35,pembayaran bunga dari aktivitas operasi,3,3,Pembayaran bunga dari aktivitas operasi
36,pembayaran dividen dari aktivitas operasi,3,3,Pembayaran dividen dari aktivitas operasi
37,pembayaran kas dari aktivitas operasi,3,3,Pembayaran kas dari aktivitas operasi
38,penerimaan (pengeluaran) kas lainnya dari akti...,3,3,Penerimaan (pengeluaran) kas lainnya dari akti...
39,penerimaan bunga dari aktivitas operasi,3,3,Penerimaan bunga dari aktivitas operasi
40,penerimaan dividen dari aktivitas operasi,3,3,Penerimaan dividen dari aktivitas operasi
41,penerimaan kas dari aktivitas operasi,3,3,Penerimaan kas dari aktivitas operasi
42,penerimaan kas lainnya dari aktivitas operasi,3,3,Penerimaan kas lainnya dari aktivitas operasi
43,penerimaan pengembalian (pembayaran) pajak pen...,3,3,Penerimaan pengembalian (pembayaran) pajak pen...
50,total net cash flows received from (used in) f...,3,3,Total net cash flows received from (used in) f...
51,total net cash flows received from (used in) i...,3,3,Total net cash flows received from (used in) i...
52,total net cash flows received from (used in) o...,3,3,Total net cash flows received from (used in) o...
15,"gains (losses) on cash flow hedges, after tax",2,2,"Gains (losses) on cash flow hedges, after tax"
27,"keuntungan (kerugian) lindung nilai arus kas, ...",2,2,"Keuntungan (kerugian) lindung nilai arus kas, ..."
45,penyesuaian reklasifikasi atas lindung nilai a...,2,2,Penyesuaian reklasifikasi atas lindung nilai a...
46,reclassification adjustments on cash flow hedg...,2,2,Reclassification adjustments on cash flow hedg...
16,"gains (losses) on cash flow hedges, before tax",1,1,"Gains (losses) on cash flow hedges, before tax"
17,imbalan pasca kerja perusahaan membukukan imba...,1,1,Imbalan pasca kerja\n Perusahaan membukukan im...
26,"keuntungan (kerugian) lindung nilai arus kas, ...",1,1,"Keuntungan (kerugian) lindung nilai arus kas, ..."
29,laporan keuangan telah disusun sesuai dengan s...,1,1,Laporan keuangan telah disusun sesuai dengan S...
34,"pada setiap akhir periode pelaporan, perusahaa...",1,1,"Pada setiap akhir periode pelaporan, Perusahaa..."
44,penyesuaian reklasifikasi atas lindung nilai a...,1,1,Penyesuaian reklasifikasi atas lindung nilai a...
47,reclassification adjustments on cash flow hedg...,1,1,Reclassification adjustments on cash flow hedg...

In [19]:
TARGET_PROFIT_PATTERNS = (
    r"gross profit"
    r"|laba bruto"
    r"|laba kotor"
    r"|operating profit"
    r"|profit from operations"
    r"|operating income"
    r"|laba usaha"
    r"|laba operasi"
    r"|profit for the period"
    r"|profit for the year"
    r"|net income"
    r"|net profit"
    r"|laba periode berjalan"
    r"|laba tahun berjalan"
    r"|laba bersih"
)

target_profit_test_df = (
    test_labels_df[
        test_labels_df["normalized_label"]
        .str.contains(
            TARGET_PROFIT_PATTERNS,
            regex=True,
            na=False
        )
    ]
    .copy()
)

print(
    "Target profit labels found:",
    len(target_profit_test_df)
)

display(
    target_profit_test_df[
        [
            "ticker",
            "source_sheet",
            "row_number",
            "source_label",
            "normalized_label"
        ]
    ].head(300)
)

Target profit labels found: 7

,ticker,source_sheet,row_number,source_label,normalized_label
554,ZYRX,1321000,8,Jumlah laba bruto,jumlah laba bruto
555,ZYRX,1321000,8,Total gross profit,total gross profit
8731,ZONE,1311000,8,Jumlah laba bruto,jumlah laba bruto
8732,ZONE,1311000,8,Total gross profit,total gross profit
9522,ZONE,1610000,26,Laba per saham dihitung dengan membagi laba ta...,laba per saham dihitung dengan membagi laba ta...
16887,ZINC,1311000,8,Jumlah laba bruto,jumlah laba bruto
16888,ZINC,1311000,8,Total gross profit,total gross profit

In [20]:
target_profit_summary = (
    target_profit_test_df
    .groupby("normalized_label")
    .agg(
        occurrences=(
            "normalized_label",
            "size"
        ),
        unique_tickers=(
            "ticker",
            "nunique"
        ),
        example_label=(
            "source_label",
            "first"
        )
    )
    .reset_index()
    .sort_values(
        [
            "unique_tickers",
            "occurrences"
        ],
        ascending=[
            False,
            False
        ]
    )
)

display(
    target_profit_summary.head(300)
)

,normalized_label,occurrences,unique_tickers,example_label
0,jumlah laba bruto,3,3,Jumlah laba bruto
2,total gross profit,3,3,Total gross profit
1,laba per saham dihitung dengan membagi laba ta...,1,1,Laba per saham dihitung dengan membagi laba ta...

In [21]:
TARGET_OCF_PATTERNS = (
    r"net cash flows received from \(used in\) operating activities"
    r"|total net cash flows received from \(used in\) operating activities"
    r"|jumlah arus kas bersih yang diperoleh dari \(digunakan untuk\) aktivitas operasi"
)

target_ocf_test_df = (
    test_labels_df[
        test_labels_df["normalized_label"]
        .str.contains(
            TARGET_OCF_PATTERNS,
            regex=True,
            na=False
        )
    ]
    .copy()
)

display(
    target_ocf_test_df[
        [
            "ticker",
            "source_sheet",
            "row_number",
            "source_label",
            "normalized_label"
        ]
    ]
)

,ticker,source_sheet,row_number,source_label,normalized_label
1006,ZYRX,1510000,39,Net cash flows received from (used in) operati...,net cash flows received from (used in) operati...
1021,ZYRX,1510000,47,Jumlah arus kas bersih yang diperoleh dari (di...,jumlah arus kas bersih yang diperoleh dari (di...
1022,ZYRX,1510000,47,Total net cash flows received from (used in) o...,total net cash flows received from (used in) o...
9179,ZONE,1510000,39,Net cash flows received from (used in) operati...,net cash flows received from (used in) operati...
9194,ZONE,1510000,47,Jumlah arus kas bersih yang diperoleh dari (di...,jumlah arus kas bersih yang diperoleh dari (di...
9195,ZONE,1510000,47,Total net cash flows received from (used in) o...,total net cash flows received from (used in) o...
17335,ZINC,1510000,39,Net cash flows received from (used in) operati...,net cash flows received from (used in) operati...
17350,ZINC,1510000,47,Jumlah arus kas bersih yang diperoleh dari (di...,jumlah arus kas bersih yang diperoleh dari (di...
17351,ZINC,1510000,47,Total net cash flows received from (used in) o...,total net cash flows received from (used in) o...

In [22]:
from collections import defaultdict

label_stats = {}

total_files = len(valid_files_df)
CHECKPOINT_EVERY = 250

for i, (_, row) in enumerate(
    tqdm(
        valid_files_df.iterrows(),
        total=total_files,
        desc="Discovering labels",
        unit="file"
    ),
    start=1
):

    file_results = extract_labels_from_file(row)

    seen_labels_in_file = set()
    seen_labels_in_ticker = set()

    ticker = row["ticker"]
    source_file = row["file_name"]

    for item in file_results:

        label = item["normalized_label"]

        if label not in label_stats:
            label_stats[label] = {
                "occurrences": 0,
                "files": set(),
                "tickers": set(),
                "example_label": item["source_label"]
            }

        label_stats[label]["occurrences"] += 1
        label_stats[label]["files"].add(source_file)
        label_stats[label]["tickers"].add(ticker)

    if i % CHECKPOINT_EVERY == 0:

        checkpoint_rows = []

        for label, stats in label_stats.items():

            checkpoint_rows.append({
                "normalized_label": label,
                "occurrences": stats["occurrences"],
                "unique_files": len(stats["files"]),
                "unique_tickers": len(stats["tickers"]),
                "example_label": stats["example_label"]
            })

        checkpoint_df = pd.DataFrame(checkpoint_rows)

        checkpoint_df.to_csv(
            CHECKPOINT_FILE,
            index=False
        )

        tqdm.write(
            f"Checkpoint saved: "
            f"{i:,}/{total_files:,} files | "
            f"{len(checkpoint_df):,} unique labels"
        )

Discovering labels:   2%|▏         | 250/15821 [03:50<2:59:49,  1.44file/s]

Checkpoint saved: 250/15,821 files | 9,776 unique labels

Discovering labels:   3%|▎         | 500/15821 [06:35<3:36:02,  1.18file/s]

Checkpoint saved: 500/15,821 files | 16,173 unique labels

Discovering labels:   5%|▍         | 750/15821 [08:52<2:42:50,  1.54file/s]

Checkpoint saved: 750/15,821 files | 22,334 unique labels

Discovering labels:   6%|▋         | 1000/15821 [11:01<2:55:10,  1.41file/s]

Checkpoint saved: 1,000/15,821 files | 25,029 unique labels

Discovering labels:   8%|▊         | 1250/15821 [13:14<2:52:49,  1.41file/s]

Checkpoint saved: 1,250/15,821 files | 27,920 unique labels

Discovering labels:   9%|▉         | 1500/15821 [15:34<3:18:48,  1.20file/s]

Checkpoint saved: 1,500/15,821 files | 30,023 unique labels

Discovering labels:  10%|▉         | 1551/15821 [16:01<1:58:53,  2.00file/s]e:\BINUS_CODING\Ai Builders Hackhaton\AI-Builders-Hackhaton-2026-Backend\venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
Discovering labels:  11%|█         | 1750/15821 [17:47<2:11:52,  1.78file/s]

Checkpoint saved: 1,750/15,821 files | 31,962 unique labels

Discovering labels:  13%|█▎        | 2000/15821 [20:06<3:09:40,  1.21file/s]

Checkpoint saved: 2,000/15,821 files | 34,023 unique labels

Discovering labels:  14%|█▍        | 2250/15821 [22:30<3:03:15,  1.23file/s]

Checkpoint saved: 2,250/15,821 files | 36,475 unique labels

Discovering labels:  16%|█▌        | 2500/15821 [24:54<3:30:13,  1.06file/s]

Checkpoint saved: 2,500/15,821 files | 38,401 unique labels

Discovering labels:  17%|█▋        | 2750/15821 [28:08<4:12:41,  1.16s/file]

Checkpoint saved: 2,750/15,821 files | 41,007 unique labels

Discovering labels:  19%|█▉        | 3000/15821 [31:27<4:41:34,  1.32s/file]

Checkpoint saved: 3,000/15,821 files | 43,595 unique labels

Discovering labels:  21%|██        | 3250/15821 [34:31<3:55:29,  1.12s/file]

Checkpoint saved: 3,250/15,821 files | 45,819 unique labels

Discovering labels:  22%|██▏       | 3500/15821 [37:27<3:39:26,  1.07s/file]

Checkpoint saved: 3,500/15,821 files | 47,766 unique labels

Discovering labels:  24%|██▎       | 3750/15821 [40:11<4:18:38,  1.29s/file]

Checkpoint saved: 3,750/15,821 files | 49,761 unique labels

Discovering labels:  25%|██▌       | 4000/15821 [45:17<9:13:58,  2.81s/file]

Checkpoint saved: 4,000/15,821 files | 52,598 unique labels

Discovering labels:  27%|██▋       | 4250/15821 [54:02<8:35:31,  2.67s/file]

Checkpoint saved: 4,250/15,821 files | 55,166 unique labels

Discovering labels:  28%|██▊       | 4500/15821 [1:03:19<8:25:02,  2.68s/file]

Checkpoint saved: 4,500/15,821 files | 57,925 unique labels

Discovering labels:  30%|███       | 4750/15821 [1:11:18<6:59:56,  2.28s/file]

Checkpoint saved: 4,750/15,821 files | 60,041 unique labels

Discovering labels:  32%|███▏      | 5000/15821 [1:19:28<11:37:45,  3.87s/file]

Checkpoint saved: 5,000/15,821 files | 62,033 unique labels

Discovering labels:  33%|███▎      | 5250/15821 [1:36:18<13:58:21,  4.76s/file]

Checkpoint saved: 5,250/15,821 files | 64,074 unique labels

Discovering labels:  35%|███▍      | 5500/15821 [1:48:33<14:29:56,  5.06s/file]

Checkpoint saved: 5,500/15,821 files | 66,573 unique labels

Discovering labels:  36%|███▋      | 5750/15821 [2:03:00<14:11:15,  5.07s/file]

Checkpoint saved: 5,750/15,821 files | 68,917 unique labels

Discovering labels:  38%|███▊      | 6000/15821 [2:18:35<13:51:50,  5.08s/file]

Checkpoint saved: 6,000/15,821 files | 71,422 unique labels

Discovering labels:  40%|███▉      | 6250/15821 [2:33:57<15:07:28,  5.69s/file]

Checkpoint saved: 6,250/15,821 files | 74,284 unique labels

Discovering labels:  41%|████      | 6500/15821 [2:50:02<13:27:56,  5.20s/file]

Checkpoint saved: 6,500/15,821 files | 76,636 unique labels

Discovering labels:  43%|████▎     | 6750/15821 [3:03:53<10:37:13,  4.21s/file]

Checkpoint saved: 6,750/15,821 files | 78,912 unique labels

Discovering labels:  44%|████▍     | 7000/15821 [3:16:57<11:16:03,  4.60s/file]

Checkpoint saved: 7,000/15,821 files | 81,049 unique labels

Discovering labels:  46%|████▌     | 7250/15821 [3:28:05<9:01:55,  3.79s/file]

Checkpoint saved: 7,250/15,821 files | 82,865 unique labels

Discovering labels:  47%|████▋     | 7500/15821 [3:35:09<6:19:02,  2.73s/file]

Checkpoint saved: 7,500/15,821 files | 83,702 unique labels

Discovering labels:  49%|████▉     | 7750/15821 [3:42:29<6:56:50,  3.10s/file]

Checkpoint saved: 7,750/15,821 files | 84,565 unique labels

Discovering labels:  51%|█████     | 8000/15821 [3:49:46<6:30:44,  3.00s/file]

Checkpoint saved: 8,000/15,821 files | 85,213 unique labels

Discovering labels:  52%|█████▏    | 8250/15821 [3:57:16<9:04:24,  4.31s/file]

Checkpoint saved: 8,250/15,821 files | 85,919 unique labels

Discovering labels:  54%|█████▎    | 8500/15821 [4:04:15<5:07:23,  2.52s/file]

Checkpoint saved: 8,500/15,821 files | 86,463 unique labels

Discovering labels:  55%|█████▌    | 8750/15821 [4:11:51<8:16:07,  4.21s/file]

Checkpoint saved: 8,750/15,821 files | 87,283 unique labels

Discovering labels:  57%|█████▋    | 9000/15821 [4:19:22<7:46:44,  4.11s/file]

Checkpoint saved: 9,000/15,821 files | 88,039 unique labels

Discovering labels:  58%|█████▊    | 9250/15821 [4:27:11<7:05:11,  3.88s/file]

Checkpoint saved: 9,250/15,821 files | 88,821 unique labels

Discovering labels:  60%|██████    | 9500/15821 [4:35:20<7:41:24,  4.38s/file]

Checkpoint saved: 9,500/15,821 files | 89,565 unique labels

Discovering labels:  62%|██████▏   | 9750/15821 [4:43:09<6:26:52,  3.82s/file]

Checkpoint saved: 9,750/15,821 files | 90,459 unique labels

Discovering labels:  63%|██████▎   | 10000/15821 [4:51:48<9:46:02,  6.04s/file]

Checkpoint saved: 10,000/15,821 files | 91,129 unique labels

Discovering labels:  65%|██████▍   | 10250/15821 [5:00:12<6:36:31,  4.27s/file]

Checkpoint saved: 10,250/15,821 files | 91,734 unique labels

Discovering labels:  66%|██████▋   | 10500/15821 [5:03:32<4:14:57,  2.87s/file]

Checkpoint saved: 10,500/15,821 files | 91,769 unique labels

Discovering labels:  68%|██████▊   | 10750/15821 [5:06:53<3:44:57,  2.66s/file]

Checkpoint saved: 10,750/15,821 files | 91,769 unique labels

Discovering labels:  70%|██████▉   | 11000/15821 [5:10:03<4:42:23,  3.51s/file]

Checkpoint saved: 11,000/15,821 files | 91,782 unique labels

Discovering labels:  71%|███████   | 11250/15821 [5:13:17<3:49:48,  3.02s/file]

Checkpoint saved: 11,250/15,821 files | 91,782 unique labels

Discovering labels:  73%|███████▎  | 11500/15821 [5:16:46<3:30:41,  2.93s/file]

Checkpoint saved: 11,500/15,821 files | 91,790 unique labels

Discovering labels:  74%|███████▍  | 11750/15821 [5:19:51<4:05:00,  3.61s/file]

Checkpoint saved: 11,750/15,821 files | 91,790 unique labels

Discovering labels:  76%|███████▌  | 12000/15821 [5:23:27<3:43:53,  3.52s/file]

Checkpoint saved: 12,000/15,821 files | 91,790 unique labels

Discovering labels:  77%|███████▋  | 12250/15821 [5:27:36<3:05:42,  3.12s/file]

Checkpoint saved: 12,250/15,821 files | 91,830 unique labels

Discovering labels:  79%|███████▉  | 12500/15821 [5:31:17<3:26:04,  3.72s/file]

Checkpoint saved: 12,500/15,821 files | 91,830 unique labels

Discovering labels:  81%|████████  | 12750/15821 [5:35:04<3:11:59,  3.75s/file]

Checkpoint saved: 12,750/15,821 files | 91,830 unique labels

Discovering labels:  82%|████████▏ | 13000/15821 [5:38:15<3:09:37,  4.03s/file]

Checkpoint saved: 13,000/15,821 files | 91,830 unique labels

Discovering labels:  84%|████████▎ | 13250/15821 [5:41:30<2:01:32,  2.84s/file]

Checkpoint saved: 13,250/15,821 files | 91,839 unique labels

Discovering labels:  85%|████████▌ | 13500/15821 [5:44:23<1:44:28,  2.70s/file]

Checkpoint saved: 13,500/15,821 files | 91,839 unique labels

Discovering labels:  87%|████████▋ | 13750/15821 [5:47:27<1:42:02,  2.96s/file]

Checkpoint saved: 13,750/15,821 files | 91,839 unique labels

Discovering labels:  88%|████████▊ | 14000/15821 [5:50:18<1:19:12,  2.61s/file]

Checkpoint saved: 14,000/15,821 files | 91,839 unique labels

Discovering labels:  90%|█████████ | 14250/15821 [5:53:22<1:21:29,  3.11s/file]

Checkpoint saved: 14,250/15,821 files | 91,839 unique labels

Discovering labels:  92%|█████████▏| 14500/15821 [5:56:42<1:07:11,  3.05s/file]

Checkpoint saved: 14,500/15,821 files | 91,839 unique labels

Discovering labels:  93%|█████████▎| 14750/15821 [6:00:12<1:05:51,  3.69s/file]

Checkpoint saved: 14,750/15,821 files | 91,839 unique labels

Discovering labels:  95%|█████████▍| 15000/15821 [6:03:33<40:27,  2.96s/file]

Checkpoint saved: 15,000/15,821 files | 91,839 unique labels

Discovering labels:  96%|█████████▋| 15250/15821 [6:06:48<31:55,  3.35s/file]

Checkpoint saved: 15,250/15,821 files | 91,839 unique labels

Discovering labels:  98%|█████████▊| 15500/15821 [6:10:09<19:04,  3.57s/file]

Checkpoint saved: 15,500/15,821 files | 91,839 unique labels

Discovering labels: 100%|█████████▉| 15750/15821 [6:13:26<03:55,  3.31s/file]

Checkpoint saved: 15,750/15,821 files | 91,843 unique labels

Discovering labels: 100%|██████████| 15821/15821 [6:14:16<00:00,  1.42s/file]

In [23]:
label_summary_rows = []

for label, stats in label_stats.items():

    label_summary_rows.append({
        "normalized_label": label,
        "occurrences": stats["occurrences"],
        "unique_files": len(stats["files"]),
        "unique_tickers": len(stats["tickers"]),
        "example_label": stats["example_label"]
    })

label_summary_df = pd.DataFrame(
    label_summary_rows
)

label_summary_df = (
    label_summary_df
    .sort_values(
        [
            "unique_tickers",
            "occurrences"
        ],
        ascending=[
            False,
            False
        ]
    )
    .reset_index(drop=True)
)

display(
    label_summary_df.head(300)
)

,normalized_label,occurrences,unique_files,unique_tickers,example_label
0,aset tetap,135618,15817,948,Aset tetap
1,goodwill,47736,15817,948,Goodwill
2,ekuitas,47436,15816,948,Ekuitas
3,equity,47436,15816,948,Equity
4,saham biasa,47436,15816,948,Saham biasa
...,...,...,...,...,...
295,"bangunan dan fasilitasnya, dimiliki langsung",38696,8040,928,"Bangunan dan fasilitasnya, dimiliki langsung"
296,"building and leasehold improvement, directly o...",38696,8040,928,"Building and leasehold improvement, directly o..."
297,"mesin dan peralatan, dimiliki langsung",38696,8040,928,"Mesin dan peralatan, dimiliki langsung"
298,"machinery and equipment, directly owned",38696,8040,928,"Machinery and equipment, directly owned"
299,"alat berat, dimiliki langsung",38696,8040,928,"Alat berat, dimiliki langsung"

In [24]:
OUTPUT_FILE = Path(
    "data/idx_financial/discovery/idx_financial_label_discovery.csv"
)

label_summary_df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    "Saved to:",
    OUTPUT_FILE
)

print(
    "Unique labels:",
    len(label_summary_df)
)

Saved to: data\idx_financial_label_discovery.csv
Unique labels: 91843

In [25]:
profit_labels = label_summary_df[
    label_summary_df["normalized_label"]
    .str.contains(
        r"profit|laba|income",
        regex=True,
        na=False
    )
]

display(
    profit_labels.head(500)
)

,normalized_label,occurrences,unique_files,unique_tickers,example_label
29,saldo laba yang belum ditentukan penggunaannya,47436,15816,948,Saldo laba yang belum ditentukan penggunaannya
36,laba (rugi),31623,15810,948,Laba (rugi)
37,profit (loss),31623,15810,948,Profit (loss)
51,other comprehensive income,31619,15810,948,Other comprehensive income
124,laporan laba rugi dan penghasilan komprehensif...,20624,15816,948,Laporan laba rugi dan penghasilan komprehensif...
...,...,...,...,...,...
6878,beban pajak kini ditentukan berdasarkan laba k...,9,9,2,Beban pajak kini ditentukan berdasarkan laba\n...
6886,beban pajak penghasilan merupakan jumlah pajak...,9,9,2,Beban pajak penghasilan merupakan jumlah pajak...
6887,laba per saham dasar dihitung dengan membagi j...,9,9,2,Laba per saham dasar dihitung dengan membagi j...
6897,laba per saham dihitung dengan membagi laba be...,9,9,2,Laba per saham dihitung dengan membagi laba be...
6910,biaya dibayar di muka adalah biaya yang telah ...,9,9,2,Biaya dibayar di muka adalah biaya yang telah ...

In [26]:
cashflow_labels = label_summary_df[
    label_summary_df["normalized_label"]
    .str.contains(
        r"cash flow|arus kas|operating activit|aktivitas operasi",
        regex=True,
        na=False
    )
]

display(
    cashflow_labels.head(500)
)

,normalized_label,occurrences,unique_files,unique_tickers,example_label
23,cadangan lindung nilai arus kas,47436,15816,948,Cadangan lindung nilai arus kas
24,reserve of cash flow hedges,47436,15816,948,Reserve of cash flow hedges
128,laporan arus kas,20592,15804,948,Laporan arus kas
129,statement of cash flows,20592,15804,948,Statement of cash flows
200,arus kas dari aktivitas operasi,15807,15804,948,Arus kas dari aktivitas operasi
...,...,...,...,...,...
16417,"pada setiap akhir periode pelaporan, grup meni...",7,7,1,"Pada setiap akhir periode pelaporan, Grup meni..."
16443,"pada setiap akhir periode pelaporan, grup mene...",7,4,1,"Pada setiap akhir periode pelaporan, Grup mene..."
16620,provisi diakui jika grup memiliki kewajiban ki...,6,6,1,Provisi diakui jika Grup memiliki kewajiban ki...
16625,"pada setiap akhir periode pelaporan, perusahaa...",6,6,1,"Pada setiap akhir periode pelaporan, Perusahaa..."
16627,nilai kini atas kewajiban imbalan kerja karyaw...,6,6,1,Nilai kini atas kewajiban imbalan kerja karyaw...